using System.Globalization;using System.Security.Cryptography;using System.Text;using DocumentFormat.OpenXml.Packaging;using DocumentFormat.OpenXml.Spreadsheet;
namespace SanSo.Import;
public sealed class CommerceFileImporter(ImportRegistry registry)
{
 private const int MaxBytes=10*1024*1024;private static readonly Dictionary<string,string> Aliases=new(StringComparer.OrdinalIgnoreCase){{"order_code","order_code"},{"order id","order_code"},{"ma don","order_code"},{"mã đơn","order_code"},{"amount","amount"},{"so tien","amount"},{"số tiền","amount"},{"occurred_at","occurred_at"},{"order date","occurred_at"},{"ngay don","occurred_at"},{"ngày đơn","occurred_at"}};
 public ImportPreview PreviewCsv(string tenant,Stream input,Encoding? encoding=null){var bytes=Read(input);var checksum=Hash(bytes);var duplicate=registry.Mark(tenant,checksum);var text=(encoding??new UTF8Encoding(false,true)).GetString(RemoveUtf8Bom(bytes));var lines=text.Replace("\r\n","\n").Replace('\r','\n').Split('\n',StringSplitOptions.RemoveEmptyEntries);if(lines.Length==0)return new("CSV","csv-v1",checksum,null,[],[],["EMPTY_FILE"],duplicate);var delimiter=Detect(lines[0]);var headers=ParseLine(lines[0],delimiter).Select(Normalize).ToList();var global=ValidateHeaders(headers);var rows=new List<ImportRow>();for(var i=1;i<lines.Length;i++){var cells=ParseLine(lines[i],delimiter);rows.Add(Map(i+1,headers,cells));}return new("CSV","csv-v1",checksum,delimiter,headers,rows,global,duplicate);}
 public ImportPreview PreviewXlsx(string tenant,Stream input){var bytes=Read(input);var checksum=Hash(bytes);var duplicate=registry.Mark(tenant,checksum);using var memory=new MemoryStream(bytes);using var doc=SpreadsheetDocument.Open(memory,false);var wb=doc.WorkbookPart??throw new InvalidDataException("WORKBOOK_MISSING");var strings=wb.SharedStringTablePart?.SharedStringTable.Elements<SharedStringItem>().Select(x=>x.InnerText).ToList()??[];var sheet=wb.Workbook.Sheets?.Elements<Sheet>().FirstOrDefault()??throw new InvalidDataException("SHEET_MISSING");var part=(WorksheetPart)wb.GetPartById(sheet.Id!);var sourceRows=part.Worksheet.Descendants<Row>().ToList();if(sourceRows.Count==0)return new("XLSX","xlsx-v1",checksum,null,[],[],["EMPTY_FILE"],duplicate);List<string> Values(Row row)=>row.Elements<Cell>().Select(x=>Value(x,strings)).ToList();var headers=Values(sourceRows[0]).Select(Normalize).ToList();var global=ValidateHeaders(headers);var rows=new List<ImportRow>();foreach(var row in sourceRows.Skip(1)){var formula=row.Elements<Cell>().Any(x=>x.CellFormula is not null);var mapped=Map((int)(row.RowIndex?.Value??0),headers,Values(row));if(formula)mapped=mapped with{Errors=mapped.Errors.Append("FORMULA_NOT_ALLOWED").ToList()};rows.Add(mapped);}return new("XLSX","xlsx-v1",checksum,null,headers,rows,global,duplicate);}
 private static ImportRow Map(int number,List<string> headers,List<string> values){var raw=headers.Select((h,i)=>(h,v:i<values.Count?values[i]:"")).GroupBy(x=>x.h).ToDictionary(x=>x.Key,x=>x.Last().v,StringComparer.OrdinalIgnoreCase);var errors=new List<string>();raw.TryGetValue("order_code",out var code);if(string.IsNullOrWhiteSpace(code))errors.Add("ORDER_CODE_REQUIRED");long? amount=null;if(raw.TryGetValue("amount",out var a)){var cleaned=a.Replace(".","").Replace(",","").Replace(" ","");if(long.TryParse(cleaned,NumberStyles.Integer,CultureInfo.InvariantCulture,out var parsed))amount=parsed;else errors.Add("AMOUNT_INVALID");}else errors.Add("AMOUNT_REQUIRED");DateTimeOffset? occurred=null;if(raw.TryGetValue("occurred_at",out var d)){var formats=new[]{"yyyy-MM-dd'T'HH:mm:ssK","yyyy-MM-dd HH:mm:ss","yyyy-MM-dd","dd/MM/yyyy HH:mm:ss","dd/MM/yyyy"};if(DateTimeOffset.TryParseExact(d,formats,CultureInfo.InvariantCulture,DateTimeStyles.AssumeUniversal,out var dto))occurred=dto.Offset==TimeSpan.Zero?dto.ToOffset(TimeSpan.FromHours(7)):dto;else errors.Add("DATE_INVALID");}else errors.Add("DATE_REQUIRED");return new(number,code,amount,occurred,raw,errors);}
 private static string Value(Cell c,List<string> shared){if(c.DataType?.Value==CellValues.SharedString&&int.TryParse(c.CellValue?.Text,out var index)&&index>=0&&index<shared.Count)return shared[index];return c.CellValue?.Text??c.InnerText??"";}
 private static List<string> ValidateHeaders(List<string> h)=>new[]{"order_code","amount","occurred_at"}.Where(x=>!h.Contains(x,StringComparer.OrdinalIgnoreCase)).Select(x=>$"MISSING_COLUMN:{x}").ToList();
 private static string Normalize(string h){var cleaned=h.Trim().TrimStart('\uFEFF').ToLowerInvariant();return Aliases.GetValueOrDefault(cleaned,cleaned);}
 private static char Detect(string line)=>new[]{',',';','\t'}.OrderByDescending(x=>line.Count(c=>c==x)).First();
 private static List<string> ParseLine(string line,char delimiter){var result=new List<string>();var value=new StringBuilder();var quoted=false;for(var i=0;i<line.Length;i++){var c=line[i];if(c=='"'){if(quoted&&i+1<line.Length&&line[i+1]=='"'){value.Append('"');i++;}else quoted=!quoted;}else if(c==delimiter&&!quoted){result.Add(value.ToString());value.Clear();}else value.Append(c);}result.Add(value.ToString());return result;}
 private static byte[] Read(Stream input){if(input.CanSeek&&input.Length>MaxBytes)throw new InvalidDataException("FILE_TOO_LARGE");using var m=new MemoryStream();input.CopyTo(m);if(m.Length>MaxBytes)throw new InvalidDataException("FILE_TOO_LARGE");return m.ToArray();}private static byte[] RemoveUtf8Bom(byte[] x)=>x.Length>=3&&x[0]==0xef&&x[1]==0xbb&&x[2]==0xbf?x[3..]:x;private static string Hash(byte[] x)=>Convert.ToHexString(SHA256.HashData(x)).ToLowerInvariant();
}
