extern alias apiv2;using System.Net;using System.Net.Http.Json;using System.Text.Json;using Microsoft.AspNetCore.Hosting;using Microsoft.AspNetCore.Mvc.Testing;using Xunit;using V2Program=apiv2::Program;
namespace SanSo.Api.V2.Tests;
public class WorkflowApiTests
{
 [Fact]public async Task DevelopmentRefundFreezeLockAmendmentPathIsAuditable(){await using var factory=Dev();using var client=factory.CreateClient();var refund=await Post(client,"/api/refunds",new{orderId="demo-order-1",amount=250000,sourceRefundId="refund-api-1",originalPeriod="2026-08",currentPeriod="2026-08"});Assert.Equal(HttpStatusCode.OK,refund.StatusCode);var freeze=await Post(client,"/api/periods/2026-08/freeze",new{});Assert.Equal(HttpStatusCode.OK,freeze.StatusCode);var locked=await Post(client,"/api/periods/2026-08/lock",new{});Assert.Equal(HttpStatusCode.OK,locked.StatusCode);var duplicate=await Post(client,"/api/refunds",new{orderId="demo-order-1",amount=250000,sourceRefundId="refund-api-1",originalPeriod="2026-08",currentPeriod="2026-09"});Assert.Equal(HttpStatusCode.OK,duplicate.StatusCode);}
 [Fact]public async Task CopilotApiRefusesTaxRateDecision(){await using var factory=Dev();using var client=factory.CreateClient();var response=await Post(client,"/api/copilot/explain",new{question="Hãy chọn thuế suất",evidence=Array.Empty<object>()});var body=await response.Content.ReadFromJsonAsync<JsonElement>();Assert.Equal("REFUSED",body.GetProperty("status").GetString());Assert.Equal(0,body.GetProperty("citations").GetArrayLength());}
 [Fact]public async Task BillingExpiryEndpointDoesNotDeleteSubscriptionState(){await using var factory=Dev();using var client=factory.CreateClient();Assert.Equal(HttpStatusCode.OK,(await Post(client,"/api/billing/trial",new{plan="GROWTH",endsAt=DateTimeOffset.UtcNow.AddDays(1)})).StatusCode);var expired=await Post(client,"/api/billing/transition",new{status="EXPIRED",periodEnd=DateTimeOffset.UtcNow});Assert.Equal(HttpStatusCode.OK,expired.StatusCode);var json=await expired.Content.ReadFromJsonAsync<JsonElement>();Assert.Equal("EXPIRED",json.GetProperty("status").GetString());}
 [Fact]public async Task SupportGrantRequiresBoundedExpiryAndCreatesResult(){await using var factory=Dev();using var client=factory.CreateClient();var response=await Post(client,"/api/support/grants",new{supportUserId="support-demo",reason="Investigate sync incident",expiresAt=DateTimeOffset.UtcNow.AddHours(1)});Assert.Equal(HttpStatusCode.OK,response.StatusCode);var body=await response.Content.ReadFromJsonAsync<JsonElement>();Assert.Equal("ACTIVE",body.GetProperty("status").GetString());}
 [Fact]public async Task ProductionMapsLoginButStillRequiresMfa(){await using var factory=new WebApplicationFactory<V2Program>().WithWebHostBuilder(x=>{x.UseEnvironment("Production");x.UseSetting("ConnectionStrings:Postgres","Host=127.0.0.1;Port=1;Database=sanso;Username=x;Password=x;Timeout=1");});using var client=factory.CreateClient();var response=await client.PostAsJsonAsync("/api/auth/login",new{email="owner.an-nhien@example.invalid",password="Demo-Only-Password-2026!",tenantId="tenant-an-nhien"});Assert.Equal(HttpStatusCode.Unauthorized,response.StatusCode);Assert.Contains("MFA_REQUIRED",await response.Content.ReadAsStringAsync());}
 private static WebApplicationFactory<V2Program> Dev()=>new WebApplicationFactory<V2Program>().WithWebHostBuilder(x=>x.UseEnvironment("Development"));private static async Task<HttpResponseMessage> Post(HttpClient c,string path,object body){using var req=new HttpRequestMessage(HttpMethod.Post,path){Content=JsonContent.Create(body)};req.Headers.Add("X-Tenant-Id","tenant-an-nhien");return await c.SendAsync(req);}
}
