using Npgsql;using SanSo.Api.V2;
namespace SanSo.Api.V5;
public sealed class PostgresInventoryStoreV2(NpgsqlDataSource dataSource)
{
 public async Task<(int Available,long Version)> Reserve(string tenant,string sku,int quantity,string sourceKey,CancellationToken ct){if(quantity<=0)throw new ArgumentOutOfRangeException(nameof(quantity));await using var c=await Open(tenant,ct);await using var tx=await c.BeginTransactionAsync(System.Data.IsolationLevel.Serializable,ct);await using(var duplicate=c.CreateCommand()){duplicate.Transaction=tx;duplicate.CommandText="SELECT 1 FROM inventory_movements WHERE organization_id=$1::uuid AND source_key=$2";duplicate.Parameters.AddWithValue(tenant);duplicate.Parameters.AddWithValue(sourceKey);if(await duplicate.ExecuteScalarAsync(ct)is not null){await tx.CommitAsync(ct);return await Balance(c,tenant,sku,ct);}}
  int available;long version;Guid product;Guid location;await using(var locked=c.CreateCommand()){locked.Transaction=tx;locked.CommandText="SELECT b.on_hand-b.reserved-b.quarantine,b.version,p.id,l.id FROM inventory_balances b JOIN products p ON p.id=b.product_id JOIN inventory_locations l ON l.id=b.location_id WHERE b.organization_id=$1::uuid AND p.canonical_sku=$2 FOR UPDATE";locked.Parameters.AddWithValue(tenant);locked.Parameters.AddWithValue(sku);await using var reader=await locked.ExecuteReaderAsync(ct);if(!await reader.ReadAsync(ct))throw new KeyNotFoundException("Inventory balance not found");available=reader.GetInt32(0);version=reader.GetInt64(1);product=reader.GetGuid(2);location=reader.GetGuid(3);}if(available<quantity)throw new InventoryConflictException();
  await using(var update=c.CreateCommand()){update.Transaction=tx;update.CommandText="UPDATE inventory_balances SET reserved=reserved+$1,version=version+1 WHERE organization_id=$2::uuid AND product_id=$3 AND location_id=$4";update.Parameters.AddWithValue(quantity);update.Parameters.AddWithValue(tenant);update.Parameters.AddWithValue(product);update.Parameters.AddWithValue(location);if(await update.ExecuteNonQueryAsync(ct)!=1)throw new InvalidOperationException("INVENTORY_BALANCE_UPDATE_LOST");}
  await using(var movement=c.CreateCommand()){movement.Transaction=tx;movement.CommandText="INSERT INTO inventory_movements(organization_id,product_id,location_id,type,quantity,source_key,occurred_at) VALUES($1::uuid,$2,$3,'RESERVE',$4,$5,now())";movement.Parameters.AddWithValue(tenant);movement.Parameters.AddWithValue(product);movement.Parameters.AddWithValue(location);movement.Parameters.AddWithValue(quantity);movement.Parameters.AddWithValue(sourceKey);await movement.ExecuteNonQueryAsync(ct);}await tx.CommitAsync(ct);return(available-quantity,version+1);}
 static async Task<(int Available,long Version)> Balance(NpgsqlConnection c,string tenant,string sku,CancellationToken ct){await using var q=c.CreateCommand();q.CommandText="SELECT b.on_hand-b.reserved-b.quarantine,b.version FROM inventory_balances b JOIN products p ON p.id=b.product_id WHERE b.organization_id=$1::uuid AND p.canonical_sku=$2";q.Parameters.AddWithValue(tenant);q.Parameters.AddWithValue(sku);await using var r=await q.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))throw new KeyNotFoundException();return(r.GetInt32(0),r.GetInt64(1));}async Task<NpgsqlConnection> Open(string tenant,CancellationToken ct){var c=await dataSource.OpenConnectionAsync(ct);await using var q=c.CreateCommand();q.CommandText="SELECT set_config('app.current_organization_id',$1,false)";q.Parameters.AddWithValue(tenant);await q.ExecuteNonQueryAsync(ct);return c;}
}
