using System.Text;using Npgsql;using SanSo.Api;using SanSo.Api.Modules;using SanSo.Api.V2;
namespace SanSo.Api.V5;
public static class V5AuthorizedComposition
{
 static readonly OnboardingWorkflow Onboarding=new();static readonly NotificationCenter Notifications=new();
 public static WebApplication MapSanSoModules(this WebApplication app)
 {
  string Tenant(HttpRequest r)=>r.Headers["X-Tenant-Id"].FirstOrDefault()??throw new UnauthorizedAccessException();SessionPrincipal Require(HttpRequest r,string permission)=>IdentityEndpoints.Require(r,app.Services.GetRequiredService<IdentityService>(),permission);bool Db()=>app.Services.GetService<NpgsqlDataSource>()is not null;PostgresLifecycleStore Life()=>app.Services.GetRequiredService<PostgresLifecycleStore>();
  app.MapPost("/api/raw-events",async(HttpRequest r,V5RawBody b,RawIngestion memory,CancellationToken ct)=>{Require(r,"finance.read");return Db()?Results.Ok(await app.Services.GetRequiredService<PostgresCommerceStore>().AcceptRaw(Tenant(r),b.Source,b.EventId,b.EventType,b.SchemaVersion,b.Payload,ct)):Results.Ok(memory.Accept(Tenant(r),b.Source,b.EventId,b.EventType,b.Payload,b.SchemaVersion));});
  app.MapGet("/api/raw-events/{id}",(HttpRequest r,string id,RawIngestion memory)=>{Require(r,"finance.read");return memory.Find(Tenant(r),id)is{}x?Results.Ok(x):Results.NotFound();});
  app.MapPost("/api/tax/periods/{period}/calculate",(HttpRequest r,string period,V5TaxBody b,TaxCenter tax)=>{Require(r,"tax.review");return Results.Ok(tax.Calculate(Tenant(r),period,b.EffectiveDate,b.BasisAmount,b.PlatformWithheldAmount,b.HasRequiredProfile,b.Category));});
  app.MapPost("/api/tax/periods/{period}/transition",(HttpRequest r,string period,V5TaxTransitionBody b,TaxCenter tax)=>{Require(r,"tax.review");tax.Transition(Tenant(r),period,b.Next,b.Reason);return Results.Ok(new{status=tax.Status(Tenant(r),period).ToString()});});
  app.MapPost("/api/inventory/{sku}/seed",(HttpRequest r,string sku,V5InventorySeedBody b,InventoryService inventory)=>{Require(r,"inventory.write");return app.Environment.IsDevelopment()?Results.Ok(inventory.Seed(Tenant(r),sku,b.OnHand)):Results.NotFound();});
  app.MapPost("/api/inventory/{sku}/reserve",async(HttpRequest r,string sku,V5InventoryBody b,InventoryService memory,CancellationToken ct)=>{Require(r,"inventory.write");try{if(Db())return Results.Ok(await new PostgresInventoryStoreV3(app.Services.GetRequiredService<NpgsqlDataSource>()).Reserve(Tenant(r),sku,b.Quantity,b.SourceKey,ct));return memory.Reserve(Tenant(r),sku,b.Quantity,b.SourceKey)?Results.Ok(memory.Get(Tenant(r),sku)):Results.Conflict(new{code="INSUFFICIENT_ATP"});}catch(InventoryConflictException){return Results.Conflict(new{code="INSUFFICIENT_ATP"});}});
  app.MapPost("/api/inventory/{sku}/release",(HttpRequest r,string sku,V5InventoryBody b,InventoryService memory)=>{Require(r,"inventory.write");if(Db())return Results.Json(new{code="POSTGRES_RELEASE_NOT_IMPLEMENTED"},statusCode:501);memory.Release(Tenant(r),sku,b.Quantity,b.SourceKey);return Results.Ok(memory.Get(Tenant(r),sku));});
  app.MapGet("/api/inventory/{sku}",(HttpRequest r,string sku,InventoryService memory)=>{Require(r,"finance.read");return Db()?Results.Json(new{code="POSTGRES_INVENTORY_READ_NOT_IMPLEMENTED"},statusCode:501):Results.Ok(memory.Get(Tenant(r),sku));});
  app.MapGet("/api/exports/reconciliation.csv",(HttpRequest r,DemoStore demo)=>{Require(r,"export.sensitive");var x=TraceableExport.ReconciliationCsv(Tenant(r),demo.Reconcile(Tenant(r)));return Results.Text(x.Content,"text/csv",Encoding.UTF8);});
  app.MapPost("/api/refunds",async(HttpRequest r,V5RefundBody b,FinancialLifecycle memory,CancellationToken ct)=>{Require(r,"tax.review");return Db()?Results.Ok(await Life().Refund(Tenant(r),b.OrderId,b.Amount,b.SourceRefundId,b.OriginalPeriod,b.CurrentPeriod,ct)):Results.Ok(memory.Refund(Tenant(r),b.OrderId,b.Amount,b.SourceRefundId,b.OriginalPeriod,b.CurrentPeriod));});
  app.MapPost("/api/periods/{period}/freeze",async(HttpRequest r,string period,FinancialLifecycle memory,CancellationToken ct)=>{Require(r,"tax.review");return Db()?Results.Ok(await Life().FreezePeriod(Tenant(r),period,ct)):Results.Ok(memory.Freeze(Tenant(r),period));});
  app.MapPost("/api/periods/{period}/lock",async(HttpRequest r,string period,FinancialLifecycle memory,CancellationToken ct)=>{var p=Require(r,"tax.review");if(Db()){await Life().LockPeriod(Tenant(r),period,p.UserId,ct);return Results.NoContent();}return Results.Ok(memory.Lock(Tenant(r),period));});
  app.MapPost("/api/team/invitations",async(HttpRequest r,V5InviteBody b,TeamAndSupport memory,CancellationToken ct)=>{var p=Require(r,"organization.manage");return Db()?Results.Ok(await Life().Invite(Tenant(r),b.Email,b.Role.ToString().ToUpperInvariant(),p.UserId,b.ExpiresAt,ct)):Results.Ok(memory.Invite(Tenant(r),b.Email,b.Role,b.ExpiresAt));});
  app.MapPost("/api/support/grants",(HttpRequest r,V5SupportBody b,TeamAndSupport support,AuditTrail audit)=>{var p=Require(r,"organization.manage");var grant=support.GrantSupport(Tenant(r),b.SupportUserId,b.Reason,b.ExpiresAt,p.UserId,p.StepUpVerified);audit.Append(Tenant(r),p.UserId,"SUPPORT_ACCESS","SUPPORT_GRANT",grant.Id,b.Reason,r.HttpContext.TraceIdentifier);return Results.Ok(grant);});
  app.MapPost("/api/billing/trial",(HttpRequest r,V5TrialBody b,BillingLifecycle billing)=>{Require(r,"billing.manage");return Results.Ok(billing.StartTrial(Tenant(r),b.Plan,b.EndsAt));});app.MapPost("/api/billing/transition",async(HttpRequest r,V5BillingBody b,BillingLifecycle billing,CancellationToken ct)=>{Require(r,"billing.manage");if(Db()){await Life().SetSubscription(Tenant(r),b.Status,b.PeriodEnd,ct);return Results.NoContent();}return Results.Ok(billing.Transition(Tenant(r),b.Status,b.PeriodEnd));});
  app.MapPost("/api/copilot/explain",(HttpRequest r,V5CopilotBody b,SafeCopilot copilot)=>{Require(r,"finance.read");return Results.Ok(copilot.Explain(Tenant(r),b.Question,b.Evidence));});
  app.MapGet("/api/onboarding",(HttpRequest r)=>{Require(r,"organization.manage");return Results.Ok(new{snapshot=Onboarding.Start(Tenant(r)),persisted=false});});app.MapPost("/api/onboarding/business-profile",(HttpRequest r,BusinessProfileDraft b)=>Authorized(r,()=>Onboarding.SaveBusinessProfile(Tenant(r),b)));app.MapPost("/api/onboarding/data-source",(HttpRequest r,V5SourceBody b)=>Authorized(r,()=>Onboarding.SelectDataSource(Tenant(r),b.Mode)));app.MapPost("/api/onboarding/backfill",(HttpRequest r,V5BackfillBody b)=>Authorized(r,()=>Onboarding.SelectBackfill(Tenant(r),b.From)));app.MapPost("/api/onboarding/sku-mapping",(HttpRequest r,V5SkuBody b)=>Authorized(r,()=>Onboarding.ConfirmSkuMapping(Tenant(r),b.MappedSkuCount)));app.MapPost("/api/onboarding/opening-balances",(HttpRequest r,V5BalancesBody b)=>Authorized(r,()=>Onboarding.SaveOpeningBalances(Tenant(r),b.Balances)));app.MapPost("/api/onboarding/disclaimer",(HttpRequest r,V5DisclaimerBody b)=>Authorized(r,()=>Onboarding.ConfirmTaxDisclaimer(Tenant(r),b.Version,b.ExplicitlyConfirmed)));app.MapPost("/api/onboarding/first-reconciliation",(HttpRequest r,V5ActivationBody b)=>Authorized(r,()=>Onboarding.CompleteFirstReconciliation(Tenant(r),b.ReconciliationId,b.HasMatchedOrExplainedDiscrepancy)));
  app.MapPost("/api/notifications",(HttpRequest r,V5NotificationBody b)=>{Require(r,"organization.manage");if(!app.Environment.IsDevelopment())return Results.Json(new{code="NOTIFICATION_PERSISTENCE_REQUIRED"},statusCode:503);return Results.Ok(new{delivery=Notifications.Raise(Tenant(r),b.Type,b.Channel,b.Recipient,b.ResourceRef,b.WindowStart),persisted=false});});app.MapGet("/api/notifications",(HttpRequest r)=>{Require(r,"finance.read");return Results.Ok(new{items=Notifications.List(Tenant(r)),persisted=false});});
  return app;IResult Authorized(HttpRequest r,Func<OnboardingSnapshot> action){Require(r,"organization.manage");try{return Results.Ok(new{snapshot=action(),persisted=false});}catch(OnboardingValidationException e){return Results.BadRequest(new{code=e.Message});}}
 }
}
public record V5RawBody(string Source,string EventId,string EventType,string SchemaVersion,string Payload);public record V5TaxBody(DateOnly EffectiveDate,long BasisAmount,long? PlatformWithheldAmount,bool HasRequiredProfile,string? Category);public record V5TaxTransitionBody(TaxPeriodStatus Next,string Reason);public record V5InventorySeedBody(int OnHand);public record V5InventoryBody(int Quantity,string SourceKey);public record V5RefundBody(string OrderId,long Amount,string SourceRefundId,string OriginalPeriod,string CurrentPeriod);public record V5InviteBody(string Email,OrgRole Role,DateTimeOffset ExpiresAt);public record V5SupportBody(string SupportUserId,string Reason,DateTimeOffset ExpiresAt);public record V5TrialBody(string Plan,DateTimeOffset EndsAt);public record V5BillingBody(string Status,DateTimeOffset PeriodEnd);public record V5CopilotBody(string Question,List<EvidenceItem> Evidence);public record V5SourceBody(SourceMode Mode);public record V5BackfillBody(DateOnly From);public record V5SkuBody(int MappedSkuCount);public record V5BalancesBody(IReadOnlyList<OpeningBalanceDraft> Balances);public record V5DisclaimerBody(string Version,bool ExplicitlyConfirmed);public record V5ActivationBody(string ReconciliationId,bool HasMatchedOrExplainedDiscrepancy);public record V5NotificationBody(NotificationType Type,DeliveryChannel Channel,string Recipient,string ResourceRef,DateTimeOffset WindowStart);
