using SanSo.Api.Modules;
namespace SanSo.Api.Tests;
public class LifecycleAndCopilotTests
{
 [Fact]public void PartialRefundPostsSignedAdjustmentWithoutDeletingSale(){var book=new FinancialLifecycle();var sale=book.Post("t1","o1","SALE",1_000_000,"sale:o1","2026-08","Original source sale");var refund=book.Refund("t1","o1",250_000,"r1","2026-08","2026-08");var all=book.Entries("t1","o1");Assert.Contains(all,x=>x.Id==sale.Id&&x.Amount==1_000_000);Assert.Contains(all,x=>x.Type=="PARTIAL_REFUND"&&x.Amount==-250_000);Assert.Equal(3,all.Count);}
 [Fact]public void ReturnAfterLockedPeriodCreatesNextPeriodAdjustmentAndPreservesExport(){var book=new FinancialLifecycle();book.Post("t1","o1","SALE",500_000,"sale:o1","2026-08","sale");book.Freeze("t1","2026-08");var exported=book.Export("t1","2026-08","old-export");book.Lock("t1","2026-08");var entries=book.Refund("t1","o1",100_000,"r-cross","2026-08","2026-09");var amendment=book.Amend("t1","2026-08","2026-09","Return arrived after close");Assert.All(entries,x=>Assert.Equal("2026-09",x.Period));Assert.Equal("NEXT_PERIOD_ADJUSTMENT",entries[0].Type);Assert.Equal(exported.ExportChecksum,book.Get("t1","2026-08").ExportChecksum);Assert.Equal(book.Get("t1","2026-08").Id,amendment.AmendmentOf);}
 [Fact]public void DuplicateRefundSourceHasOneFinancialEffect(){var book=new FinancialLifecycle();book.Refund("t1","o1",100,"r1","2026-08","2026-08");book.Refund("t1","o1",100,"r1","2026-08","2026-08");Assert.Equal(-100,book.Entries("t1","o1").Sum(x=>x.Amount));}
 [Fact]public void InvitationTokenIsHashedScopedAndExpires(){var team=new TeamAndSupport();var(invite,raw)=team.Invite("t1","Accountant@Example.Invalid",OrgRole.Accountant,DateTimeOffset.UtcNow.AddHours(1));Assert.DoesNotContain(raw,invite.TokenHash);Assert.Equal("ACCEPTED",team.Accept(invite.Id,raw).Status);Assert.Throws<UnauthorizedAccessException>(()=>team.Accept(invite.Id,raw));}
 [Fact]public void SupportAccessRequiresStepUpReasonAndShortExpiry(){var team=new TeamAndSupport();Assert.Throws<UnauthorizedAccessException>(()=>team.GrantSupport("t1","support","incident",DateTimeOffset.UtcNow.AddHours(1),"owner",false));var grant=team.GrantSupport("t1","support","incident investigation",DateTimeOffset.UtcNow.AddHours(1),"owner",true);Assert.True(team.CanSupportAccess("t1","support"));team.RevokeSupport(grant.Id);Assert.False(team.CanSupportAccess("t1","support"));}
 [Fact]public void ExpiredSubscriptionStopsNewSyncButRetainsRead(){var billing=new BillingLifecycle();billing.StartTrial("t1","GROWTH",DateTimeOffset.UtcNow.AddDays(1));billing.RecordUsage("t1",10,2);billing.Transition("t1","EXPIRED",DateTimeOffset.UtcNow);Assert.False(billing.AllowsNewSync("t1",1000));Assert.True(billing.AllowsExistingRead("t1"));}
 [Fact]public void CopilotRefusesTaxRateDecisionAndCitesTenantEvidence(){var ai=new SafeCopilot();var refused=ai.Explain("t1","Chọn thuế suất nào?",[]);Assert.Equal("REFUSED",refused.Status);var explained=ai.Explain("t1","Vì sao payout lệch?",[new("raw-1","Phí sàn","Thiếu dòng 30.000")]);Assert.Equal("EXPLAINED",explained.Status);Assert.Equal(["raw-1"],explained.Citations);}
}
