using System.Security.Cryptography;using System.Text;using Npgsql;using SanSo.Api;
namespace SanSo.Api.V2;
public sealed class PostgresCommerceStore(NpgsqlDataSource dataSource)
{
 public async Task<IReadOnlyList<Order>> Orders(string tenant,CancellationToken ct){await using var c=await Open(tenant,ct);await using var q=c.CreateCommand();q.CommandText="SELECT id::text, channel, source_key, code, gross_amount, status, occurred_at FROM orders WHERE organization_id=$1::uuid ORDER BY occurred_at DESC LIMIT 200";q.Parameters.AddWithValue(tenant);var list=new List<Order>();await using var r=await q.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))list.Add(new(r.GetString(0),tenant,r.GetString(1),r.GetString(2),r.GetString(3),r.GetInt64(4),r.GetString(5),r.GetFieldValue<DateTimeOffset>(6)));return list;}
 public async Task<Reconciliation> CurrentReconciliation(string tenant,CancellationToken ct){await using var c=await Open(tenant,ct);await using var q=c.CreateCommand();q.CommandText="""
SELECT s.code,s.actual_amount,COALESCE(sum(CASE WHEN l.type='SALE' THEN l.amount ELSE 0 END),0) gross,COALESCE(sum(CASE WHEN l.type<>'SALE' THEN l.amount ELSE 0 END),0) fees
FROM settlements s LEFT JOIN ledger_lines l ON l.organization_id=s.organization_id WHERE s.organization_id=$1::uuid GROUP BY s.code,s.actual_amount,s.paid_at ORDER BY s.paid_at DESC LIMIT 1
""";q.Parameters.AddWithValue(tenant);await using var r=await q.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))throw new KeyNotFoundException("No settlement in tenant scope");var code=r.GetString(0);var actual=r.GetInt64(1);var gross=r.GetInt64(2);var fees=r.GetInt64(3);await r.CloseAsync();await using var linesCommand=c.CreateCommand();linesCommand.CommandText="SELECT o.code,l.type,l.amount,l.explanation FROM ledger_lines l LEFT JOIN orders o ON o.id=l.order_id WHERE l.organization_id=$1::uuid ORDER BY l.occurred_at,l.id";linesCommand.Parameters.AddWithValue(tenant);var lines=new List<ReconciliationLine>();await using var lr=await linesCommand.ExecuteReaderAsync(ct);while(await lr.ReadAsync(ct))lines.Add(new(lr.IsDBNull(0)?"UNALLOCATED":lr.GetString(0),lr.GetString(1),lr.GetInt64(2),lr.GetString(3)));var expected=checked(gross+fees);var difference=actual-expected;return new(code,gross,fees,0,expected,actual,difference,difference==0?"MATCHED":"NEEDS_REVIEW",lines);}
 public async Task<Dashboard> Dashboard(string tenant,CancellationToken ct){var x=await CurrentReconciliation(tenant,ct);return new(x.Gross,x.Expected,x.Actual,x.Difference,x.Status=="MATCHED"?1:0,x.Status=="NEEDS_REVIEW"?1:0,"Từ PostgreSQL · UTC source timestamps","NEEDS_REVIEW khi thiếu approved rule");}
 public async Task<(string Id,bool Duplicate,string Checksum)> AcceptRaw(string tenant,string source,string eventId,string eventType,string schemaVersion,string payload,CancellationToken ct){var checksum=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(payload))).ToLowerInvariant();await using var c=await Open(tenant,ct);await using var tx=await c.BeginTransactionAsync(ct);await using var q=c.CreateCommand();q.Transaction=tx;q.CommandText="""
INSERT INTO raw_events(organization_id,source,source_event_id,event_type,schema_version,payload,checksum) VALUES($1::uuid,$2,$3,$4,$5,$6::jsonb,$7)
ON CONFLICT(organization_id,source,source_event_id) DO NOTHING RETURNING id::text
""";q.Parameters.AddWithValue(tenant);q.Parameters.AddWithValue(source);q.Parameters.AddWithValue(eventId);q.Parameters.AddWithValue(eventType);q.Parameters.AddWithValue(schemaVersion);q.Parameters.AddWithValue(payload);q.Parameters.AddWithValue(checksum);var id=await q.ExecuteScalarAsync(ct)as string;var duplicate=id is null;if(duplicate){await using var existing=c.CreateCommand();existing.Transaction=tx;existing.CommandText="SELECT id::text,checksum FROM raw_events WHERE organization_id=$1::uuid AND source=$2 AND source_event_id=$3";existing.Parameters.AddWithValue(tenant);existing.Parameters.AddWithValue(source);existing.Parameters.AddWithValue(eventId);await using var er=await existing.ExecuteReaderAsync(ct);await er.ReadAsync(ct);id=er.GetString(0);checksum=er.GetString(1);}await tx.CommitAsync(ct);return(id!,duplicate,checksum);}
 public async Task<(int Available,long Version)> Reserve(string tenant,string sku,int quantity,string sourceKey,CancellationToken ct){if(quantity<=0)throw new ArgumentOutOfRangeException(nameof(quantity));await using var c=await Open(tenant,ct);await using var tx=await c.BeginTransactionAsync(System.Data.IsolationLevel.Serializable,ct);await using var duplicate=c.CreateCommand();duplicate.Transaction=tx;duplicate.CommandText="SELECT 1 FROM inventory_movements WHERE organization_id=$1::uuid AND source_key=$2";duplicate.Parameters.AddWithValue(tenant);duplicate.Parameters.AddWithValue(sourceKey);if(await duplicate.ExecuteScalarAsync(ct)is not null){await tx.CommitAsync(ct);return await Balance(c,tenant,sku,ct);}await using var lockBalance=c.CreateCommand();lockBalance.Transaction=tx;lockBalance.CommandText="SELECT b.on_hand-b.reserved-b.quarantine,b.version,p.id,l.id FROM inventory_balances b JOIN products p ON p.id=b.product_id JOIN inventory_locations l ON l.id=b.location_id WHERE b.organization_id=$1::uuid AND p.canonical_sku=$2 FOR UPDATE";lockBalance.Parameters.AddWithValue(tenant);lockBalance.Parameters.AddWithValue(sku);await using var br=await lockBalance.ExecuteReaderAsync(ct);if(!await br.ReadAsync(ct))throw new KeyNotFoundException("Inventory balance not found");var available=br.GetInt32(0);var version=br.GetInt64(1);var product=br.GetGuid(2);var location=br.GetGuid(3);await br.CloseAsync();if(available<quantity)throw new InventoryConflictException();await using var update=c.CreateCommand();update.Transaction=tx;update.CommandText="UPDATE inventory_balances SET reserved=reserved+$1,version=version+1 WHERE organization_id=$2::uuid AND product_id=$3 AND location_id=$4;INSERT INTO inventory_movements(organization_id,product_id,location_id,type,quantity,source_key,occurred_at) VALUES($2::uuid,$3,$4,'RESERVE',$1,$5,now())";update.Parameters.AddWithValue(quantity);update.Parameters.AddWithValue(tenant);update.Parameters.AddWithValue(product);update.Parameters.AddWithValue(location);update.Parameters.AddWithValue(sourceKey);await update.ExecuteNonQueryAsync(ct);await tx.CommitAsync(ct);return(available-quantity,version+1);}
 private static async Task<(int Available,long Version)> Balance(NpgsqlConnection c,string tenant,string sku,CancellationToken ct){await using var q=c.CreateCommand();q.CommandText="SELECT b.on_hand-b.reserved-b.quarantine,b.version FROM inventory_balances b JOIN products p ON p.id=b.product_id WHERE b.organization_id=$1::uuid AND p.canonical_sku=$2";q.Parameters.AddWithValue(tenant);q.Parameters.AddWithValue(sku);await using var r=await q.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))throw new KeyNotFoundException();return(r.GetInt32(0),r.GetInt64(1));}
 private async Task<NpgsqlConnection> Open(string tenant,CancellationToken ct){var c=await dataSource.OpenConnectionAsync(ct);await using var q=c.CreateCommand();q.CommandText="SELECT set_config('app.current_organization_id',$1,false)";q.Parameters.AddWithValue(tenant);await q.ExecuteNonQueryAsync(ct);return c;}
}
public sealed class InventoryConflictException:Exception;
