using System.Security.Cryptography;using System.Text;using Npgsql;
namespace SanSo.Api.V2;
public sealed class PostgresLifecycleStore(NpgsqlDataSource source)
{
 public async Task<(int Inserted,string TargetPeriod)> Refund(string tenant,string orderId,long amount,string refundId,string originalPeriod,string currentPeriod,CancellationToken ct){if(amount<=0)throw new ArgumentOutOfRangeException(nameof(amount));await using var c=await Open(tenant,ct);await using var tx=await c.BeginTransactionAsync(ct);await using var status=c.CreateCommand();status.Transaction=tx;status.CommandText="SELECT status FROM tax_periods WHERE organization_id=$1::uuid AND period_key=$2";status.Parameters.AddWithValue(tenant);status.Parameters.AddWithValue(originalPeriod);var locked=(await status.ExecuteScalarAsync(ct)as string)=="LOCKED";var target=locked?currentPeriod:originalPeriod;await using var q=c.CreateCommand();q.Transaction=tx;q.CommandText="""
WITH o AS(SELECT id FROM orders WHERE organization_id=$1::uuid AND id=$2::uuid), ins AS(
 INSERT INTO ledger_lines(organization_id,order_id,type,amount,source_key,explanation,occurred_at)
 SELECT $1::uuid,o.id,$3,-$4,$5,$6,now() FROM o ON CONFLICT(organization_id,source_key) DO NOTHING RETURNING 1)
SELECT count(*)::int FROM ins
""";q.Parameters.AddWithValue(tenant);q.Parameters.AddWithValue(orderId);q.Parameters.AddWithValue(locked?"NEXT_PERIOD_ADJUSTMENT":"PARTIAL_REFUND");q.Parameters.AddWithValue(amount);q.Parameters.AddWithValue($"refund:{refundId}:principal");q.Parameters.AddWithValue($"Refund {refundId}; target period {target}; original period {originalPeriod}");var inserted=(int)(await q.ExecuteScalarAsync(ct)??0);if(locked&&inserted>0){await using var ex=c.CreateCommand();ex.Transaction=tx;ex.CommandText="INSERT INTO tax_exceptions(organization_id,period_id,code,severity,details) SELECT $1::uuid,id,'CROSS_PERIOD_RETURN','HIGH',$3::jsonb FROM tax_periods WHERE organization_id=$1::uuid AND period_key=$2";ex.Parameters.AddWithValue(tenant);ex.Parameters.AddWithValue(originalPeriod);ex.Parameters.AddWithValue($"{{\"refundId\":\"{refundId}\",\"adjustmentPeriod\":\"{target}\"}}");await ex.ExecuteNonQueryAsync(ct);}await tx.CommitAsync(ct);return(inserted,target);}
 public async Task<(string Id,string Status,string Checksum)> FreezePeriod(string tenant,string period,CancellationToken ct){await using var c=await Open(tenant,ct);await using var tx=await c.BeginTransactionAsync(ct);await using var hash=c.CreateCommand();hash.Transaction=tx;hash.CommandText="SELECT encode(digest(COALESCE(string_agg(id::text||':'||amount::text||':'||source_key,'|' ORDER BY id),''),'sha256'),'hex') FROM ledger_lines WHERE organization_id=$1::uuid AND to_char(occurred_at AT TIME ZONE 'Asia/Ho_Chi_Minh','YYYY-MM')=$2";hash.Parameters.AddWithValue(tenant);hash.Parameters.AddWithValue(period);var checksum=(string)(await hash.ExecuteScalarAsync(ct)??"");await using var upsert=c.CreateCommand();upsert.Transaction=tx;upsert.CommandText="""
INSERT INTO tax_periods(organization_id,period_key,status,input_checksum) VALUES($1::uuid,$2,'DRAFT',$3)
ON CONFLICT(organization_id,period_key) DO UPDATE SET input_checksum=EXCLUDED.input_checksum WHERE tax_periods.status<>'LOCKED'
RETURNING id::text,status
""";upsert.Parameters.AddWithValue(tenant);upsert.Parameters.AddWithValue(period);upsert.Parameters.AddWithValue(checksum);await using var r=await upsert.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))throw new InvalidOperationException("Locked period is immutable");var id=r.GetString(0);var status=r.GetString(1);await tx.CommitAsync(ct);return(id,status,checksum);}
 public async Task LockPeriod(string tenant,string period,string actor,CancellationToken ct){await using var c=await Open(tenant,ct);await using var q=c.CreateCommand();q.CommandText="UPDATE tax_periods SET status='LOCKED',locked_at=now(),locked_by=$3::uuid WHERE organization_id=$1::uuid AND period_key=$2 AND status IN('REVIEWED','READY_TO_EXPORT','EXPORTED')";q.Parameters.AddWithValue(tenant);q.Parameters.AddWithValue(period);q.Parameters.AddWithValue(actor);if(await q.ExecuteNonQueryAsync(ct)!=1)throw new InvalidOperationException("Period cannot be locked from current state");}
 public async Task<(string Id,string RawToken)> Invite(string tenant,string email,string role,string actor,DateTimeOffset expires,CancellationToken ct){if(expires<=DateTimeOffset.UtcNow)throw new ArgumentException();var raw=Convert.ToHexString(RandomNumberGenerator.GetBytes(32));var hash=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(raw)));await using var c=await Open(tenant,ct);await using var q=c.CreateCommand();q.CommandText="INSERT INTO invitations(organization_id,email,role,token_hash,expires_at,invited_by) VALUES($1::uuid,lower($2),$3,$4,$5,$6::uuid) RETURNING id::text";q.Parameters.AddWithValue(tenant);q.Parameters.AddWithValue(email);q.Parameters.AddWithValue(role);q.Parameters.AddWithValue(hash);q.Parameters.AddWithValue(expires);q.Parameters.AddWithValue(actor);return((string)(await q.ExecuteScalarAsync(ct)??throw new InvalidOperationException()),raw);}
 public async Task SetSubscription(string tenant,string status,DateTimeOffset periodEnd,CancellationToken ct){await using var c=await Open(tenant,ct);await using var q=c.CreateCommand();q.CommandText="UPDATE subscriptions SET status=$2,current_period_end=$3 WHERE organization_id=$1::uuid";q.Parameters.AddWithValue(tenant);q.Parameters.AddWithValue(status);q.Parameters.AddWithValue(periodEnd);if(await q.ExecuteNonQueryAsync(ct)!=1)throw new KeyNotFoundException("Subscription not found");}
 private async Task<NpgsqlConnection> Open(string tenant,CancellationToken ct){var c=await source.OpenConnectionAsync(ct);await using var q=c.CreateCommand();q.CommandText="SELECT set_config('app.current_organization_id',$1,false)";q.Parameters.AddWithValue(tenant);await q.ExecuteNonQueryAsync(ct);return c;}
}
