using Npgsql;using SanSo.Api;using SanSo.Api.Modules;using SanSo.Api.V2;
var builder=WebApplication.CreateBuilder(args);var cs=builder.Configuration.GetConnectionString("Postgres")??Environment.GetEnvironmentVariable("SANSO_POSTGRES");if(string.IsNullOrWhiteSpace(cs))cs=null;if(!builder.Environment.IsDevelopment()&&string.IsNullOrWhiteSpace(cs))throw new InvalidOperationException("Production requires SANSO_POSTGRES/ConnectionStrings:Postgres");if(!string.IsNullOrWhiteSpace(cs)){builder.Services.AddSingleton(NpgsqlDataSource.Create(cs));builder.Services.AddSingleton<PostgresCommerceStore>();builder.Services.AddSingleton<PostgresLifecycleStore>();}builder.Services.AddSingleton<DemoStore>();builder.Services.AddSingleton<IdentityService>();builder.Services.AddSingleton<TaxCenter>();builder.Services.AddSingleton<AuditTrail>();builder.Services.AddSingleton<FinancialLifecycle>();builder.Services.AddSingleton<TeamAndSupport>();builder.Services.AddSingleton<BillingLifecycle>();builder.Services.AddSingleton<SafeCopilot>();builder.Services.AddSingleton<ReliableSync>();builder.Services.AddCors(x=>x.AddDefaultPolicy(p=>p.WithOrigins("http://localhost:5173","http://127.0.0.1:5174").AllowAnyHeader().AllowAnyMethod()));var app=builder.Build();app.UseMiddleware<SafeProblemMiddleware>();app.UseCors();app.MapIdentity();
string Tenant(HttpRequest r)=>r.HttpContext.Items["TenantId"]as string??r.Headers["X-Tenant-Id"].FirstOrDefault()??"tenant-an-nhien";SessionPrincipal? Principal(HttpRequest r)=>r.HttpContext.Items["SessionPrincipal"]as SessionPrincipal;bool Db()=>!string.IsNullOrWhiteSpace(cs);PostgresCommerceStore Pg()=>app.Services.GetRequiredService<PostgresCommerceStore>();PostgresLifecycleStore Life()=>app.Services.GetRequiredService<PostgresLifecycleStore>();
app.MapGet("/health",async(CancellationToken ct)=>{if(!Db())return Results.Ok(new{status="degraded",database="not-configured",mode="development-demo"});try{await using var c=await app.Services.GetRequiredService<NpgsqlDataSource>().OpenConnectionAsync(ct);await using var q=c.CreateCommand();q.CommandText="SELECT 1";await q.ExecuteScalarAsync(ct);return Results.Ok(new{status="ok",database="postgresql"});}catch{return Results.Json(new{status="unhealthy",database="unavailable"},statusCode:503);}});
app.MapPost("/api/imports/demo",(HttpRequest r,DemoStore demo)=>{if(!app.Environment.IsDevelopment())return Results.NotFound();return Results.Ok(demo.ImportDemo(Tenant(r)));});
app.MapGet("/api/dashboard",async(HttpRequest r,DemoStore demo,CancellationToken ct)=>Db()?Results.Ok(await Pg().Dashboard(Tenant(r),ct)):Results.Ok(demo.Dashboard(Tenant(r))));app.MapGet("/api/orders",async(HttpRequest r,DemoStore demo,CancellationToken ct)=>Db()?Results.Ok(await Pg().Orders(Tenant(r),ct)):Results.Ok(demo.Orders(Tenant(r))));app.MapGet("/api/reconciliations/current",async(HttpRequest r,DemoStore demo,CancellationToken ct)=>Db()?Results.Ok(await Pg().CurrentReconciliation(Tenant(r),ct)):Results.Ok(demo.Reconcile(Tenant(r))));
app.MapPost("/api/raw-events",async(HttpRequest r,RawRequest b,CancellationToken ct)=>Db()?Results.Ok(await Pg().AcceptRaw(Tenant(r),b.Source,b.EventId,b.EventType,b.SchemaVersion,b.Payload,ct)):Results.Json(new{code="DATABASE_REQUIRED"},statusCode:503));
app.MapPost("/api/inventory/{sku}/reserve",async(HttpRequest r,string sku,ReserveRequest b,CancellationToken ct)=>{if(!Db())return Results.Json(new{code="DATABASE_REQUIRED"},statusCode:503);try{return Results.Ok(await Pg().Reserve(Tenant(r),sku,b.Quantity,b.SourceKey,ct));}catch(InventoryConflictException){return Results.Conflict(new{code="INSUFFICIENT_ATP"});}});
app.MapPost("/api/refunds",async(HttpRequest r,RefundRequest b,FinancialLifecycle memory,CancellationToken ct)=>{if(Db())return Results.Ok(await Life().Refund(Tenant(r),b.OrderId,b.Amount,b.SourceRefundId,b.OriginalPeriod,b.CurrentPeriod,ct));return app.Environment.IsDevelopment()?Results.Ok(memory.Refund(Tenant(r),b.OrderId,b.Amount,b.SourceRefundId,b.OriginalPeriod,b.CurrentPeriod)):Results.Json(new{code="DATABASE_REQUIRED"},statusCode:503);});
app.MapPost("/api/periods/{period}/freeze",async(HttpRequest r,string period,FinancialLifecycle memory,CancellationToken ct)=>Db()?Results.Ok(await Life().FreezePeriod(Tenant(r),period,ct)):Results.Ok(memory.Freeze(Tenant(r),period)));
app.MapPost("/api/periods/{period}/lock",async(HttpRequest r,string period,FinancialLifecycle memory,CancellationToken ct)=>{if(Db()){var actor=Principal(r)?.UserId??throw new UnauthorizedAccessException();await Life().LockPeriod(Tenant(r),period,actor,ct);return Results.NoContent();}return Results.Ok(memory.Lock(Tenant(r),period));});
app.MapPost("/api/team/invitations",async(HttpRequest r,InviteRequest b,TeamAndSupport memory,CancellationToken ct)=>{if(Db()){var actor=Principal(r)?.UserId??throw new UnauthorizedAccessException();return Results.Ok(await Life().Invite(Tenant(r),b.Email,b.Role.ToString().ToUpperInvariant(),actor,b.ExpiresAt,ct));}return Results.Ok(memory.Invite(Tenant(r),b.Email,b.Role,b.ExpiresAt));});
app.MapPost("/api/support/grants",(HttpRequest r,SupportGrantRequest b,TeamAndSupport support,AuditTrail audit)=>{var p=Principal(r)??new SessionPrincipal("demo-owner",Tenant(r),OrgRole.Owner,true,DateTimeOffset.UtcNow.AddHours(1));var grant=support.GrantSupport(Tenant(r),b.SupportUserId,b.Reason,b.ExpiresAt,p.UserId,p.StepUpVerified);audit.Append(Tenant(r),p.UserId,"SUPPORT_ACCESS","SUPPORT_GRANT",grant.Id,b.Reason,r.HttpContext.TraceIdentifier);return Results.Ok(grant);});
app.MapPost("/api/billing/trial",(HttpRequest r,TrialRequest b,BillingLifecycle billing)=>Results.Ok(billing.StartTrial(Tenant(r),b.Plan,b.EndsAt)));app.MapPost("/api/billing/transition",async(HttpRequest r,BillingTransitionRequest b,BillingLifecycle billing,CancellationToken ct)=>{if(Db()){await Life().SetSubscription(Tenant(r),b.Status,b.PeriodEnd,ct);return Results.NoContent();}return Results.Ok(billing.Transition(Tenant(r),b.Status,b.PeriodEnd));});
app.MapPost("/api/tax/periods/{period}/calculate",(HttpRequest r,string period,TaxRequest b,TaxCenter tax)=>Results.Ok(tax.Calculate(Tenant(r),period,b.EffectiveDate,b.BasisAmount,b.PlatformWithheldAmount,b.HasRequiredProfile,b.Category)));
app.MapPost("/api/copilot/explain",(HttpRequest r,CopilotRequest b,SafeCopilot ai)=>Results.Ok(ai.Explain(Tenant(r),b.Question,b.Evidence)));
app.MapGet("/api/exports/reconciliation.csv",async(HttpRequest r,DemoStore demo,CancellationToken ct)=>{var rec=Db()?await Pg().CurrentReconciliation(Tenant(r),ct):demo.Reconcile(Tenant(r));var x=TraceableExport.ReconciliationCsv(Tenant(r),rec);return Results.Text(x.Content,"text/csv",Encoding.UTF8);});
app.Run();public partial class Program{}
record RawRequest(string Source,string EventId,string EventType,string Payload,string SchemaVersion="1");record ReserveRequest(int Quantity,string SourceKey);record RefundRequest(string OrderId,long Amount,string SourceRefundId,string OriginalPeriod,string CurrentPeriod);record InviteRequest(string Email,OrgRole Role,DateTimeOffset ExpiresAt);record SupportGrantRequest(string SupportUserId,string Reason,DateTimeOffset ExpiresAt);record TrialRequest(string Plan,DateTimeOffset EndsAt);record BillingTransitionRequest(string Status,DateTimeOffset PeriodEnd);record TaxRequest(DateOnly EffectiveDate,long BasisAmount,long? PlatformWithheldAmount,bool HasRequiredProfile,string? Category);record CopilotRequest(string Question,List<EvidenceItem> Evidence);
