using Npgsql;using SanSo.Api;using SanSo.Api.Modules;using SanSo.Api.V2;
var builder=WebApplication.CreateBuilder(args);var cs=builder.Configuration.GetConnectionString("Postgres")??Environment.GetEnvironmentVariable("SANSO_POSTGRES");if(string.IsNullOrWhiteSpace(cs))cs=null;if(!builder.Environment.IsDevelopment()&&string.IsNullOrWhiteSpace(cs))throw new InvalidOperationException("Production requires SANSO_POSTGRES/ConnectionStrings:Postgres");if(!string.IsNullOrWhiteSpace(cs))builder.Services.AddSingleton(NpgsqlDataSource.Create(cs));builder.Services.AddSingleton<PostgresCommerceStore>();builder.Services.AddSingleton<DemoStore>();builder.Services.AddSingleton<IdentityService>();builder.Services.AddSingleton<TaxCenter>();builder.Services.AddSingleton<AuditTrail>();builder.Services.AddCors(x=>x.AddDefaultPolicy(p=>p.WithOrigins("http://localhost:5173","http://127.0.0.1:5174").AllowAnyHeader().AllowAnyMethod()));var app=builder.Build();app.UseMiddleware<SafeProblemMiddleware>();app.UseCors();
string Tenant(HttpRequest r)=>r.HttpContext.Items["TenantId"]as string??r.Headers["X-Tenant-Id"].FirstOrDefault()??"tenant-an-nhien";bool Db()=>!string.IsNullOrWhiteSpace(cs);
app.MapGet("/health",async(CancellationToken ct)=>{if(!Db())return Results.Ok(new{status="degraded",database="not-configured",mode="development-demo"});try{await using var c=await app.Services.GetRequiredService<NpgsqlDataSource>().OpenConnectionAsync(ct);await using var q=c.CreateCommand();q.CommandText="SELECT 1";await q.ExecuteScalarAsync(ct);return Results.Ok(new{status="ok",database="postgresql"});}catch{return Results.Json(new{status="unhealthy",database="unavailable"},statusCode:503);}});
app.MapGet("/api/dashboard",async(HttpRequest r,PostgresCommerceStore pg,DemoStore demo,CancellationToken ct)=>Db()?Results.Ok(await pg.Dashboard(Tenant(r),ct)):Results.Ok(demo.Dashboard(Tenant(r))));
app.MapGet("/api/orders",async(HttpRequest r,PostgresCommerceStore pg,DemoStore demo,CancellationToken ct)=>Db()?Results.Ok(await pg.Orders(Tenant(r),ct)):Results.Ok(demo.Orders(Tenant(r))));
app.MapGet("/api/reconciliations/current",async(HttpRequest r,PostgresCommerceStore pg,DemoStore demo,CancellationToken ct)=>Db()?Results.Ok(await pg.CurrentReconciliation(Tenant(r),ct)):Results.Ok(demo.Reconcile(Tenant(r))));
app.MapPost("/api/raw-events",async(HttpRequest r,RawRequest b,PostgresCommerceStore pg,CancellationToken ct)=>Db()?Results.Ok(await pg.AcceptRaw(Tenant(r),b.Source,b.EventId,b.EventType,b.SchemaVersion,b.Payload,ct)):Results.Json(new{code="DATABASE_REQUIRED"},statusCode:503));
app.MapPost("/api/inventory/{sku}/reserve",async(HttpRequest r,string sku,ReserveRequest b,PostgresCommerceStore pg,CancellationToken ct)=>{if(!Db())return Results.Json(new{code="DATABASE_REQUIRED"},statusCode:503);try{return Results.Ok(await pg.Reserve(Tenant(r),sku,b.Quantity,b.SourceKey,ct));}catch(InventoryConflictException){return Results.Conflict(new{code="INSUFFICIENT_ATP"});}});
app.MapPost("/api/tax/periods/{period}/calculate",(HttpRequest r,string period,TaxRequest b,TaxCenter tax)=>Results.Ok(tax.Calculate(Tenant(r),period,b.EffectiveDate,b.BasisAmount,b.PlatformWithheldAmount,b.HasRequiredProfile,b.Category)));
app.Run();public partial class Program{}
record RawRequest(string Source,string EventId,string EventType,string Payload,string SchemaVersion="1");record ReserveRequest(int Quantity,string SourceKey);record TaxRequest(DateOnly EffectiveDate,long BasisAmount,long? PlatformWithheldAmount,bool HasRequiredProfile,string? Category);
