using System.Collections.Concurrent;using System.Security.Cryptography;using System.Text;using System.Text.Json;
namespace SanSo.Api.Modules;
public record FinanceEntry(string Id,string TenantId,string OrderId,string Type,long Amount,string Currency,string SourceKey,string? ReversalOf,string Period,string Explanation,DateTimeOffset CreatedAt);
public record PeriodSnapshot(string Id,string TenantId,string Period,int Version,string Status,string InputChecksum,DateTimeOffset FrozenAt,string? ExportChecksum=null,string? AmendmentOf=null);
public sealed class FinancialLifecycle
{
 private readonly ConcurrentDictionary<string,FinanceEntry> entries=new();private readonly ConcurrentDictionary<string,PeriodSnapshot> periods=new();
 public FinanceEntry Post(string tenant,string order,string type,long amount,string sourceKey,string period,string explanation,string? reversalOf=null){if(string.IsNullOrWhiteSpace(explanation))throw new ArgumentException("Explanation required");var key=$"{tenant}|{sourceKey}";var e=new FinanceEntry(Guid.NewGuid().ToString(),tenant,order,type,amount,"VND",sourceKey,reversalOf,period,explanation,DateTimeOffset.UtcNow);return entries.GetOrAdd(key,e);}
 public IReadOnlyList<FinanceEntry> Refund(string tenant,string order,long amount,string sourceRefundId,string originalPeriod,string currentPeriod){if(amount<=0)throw new ArgumentOutOfRangeException(nameof(amount));var target=IsLocked(tenant,originalPeriod)?currentPeriod:originalPeriod;var kind=target==originalPeriod?"PARTIAL_REFUND":"NEXT_PERIOD_ADJUSTMENT";return[Post(tenant,order,kind,-amount,$"refund:{sourceRefundId}:principal",target,$"Refund source {sourceRefundId}; original period {originalPeriod}"),Post(tenant,order,"REFUND_AUDIT_MARKER",0,$"refund:{sourceRefundId}:marker",target,$"Cross-period={target!=originalPeriod}; original period retained")];}
 public PeriodSnapshot Freeze(string tenant,string period){var input=entries.Values.Where(x=>x.TenantId==tenant&&x.Period==period).OrderBy(x=>x.Id).Select(x=>new{x.Id,x.Amount,x.Type,x.SourceKey});var checksum=Hash(JsonSerializer.Serialize(input));var key=$"{tenant}|{period}";return periods.AddOrUpdate(key,_=>new(Guid.NewGuid().ToString(),tenant,period,1,"FROZEN",checksum,DateTimeOffset.UtcNow),(_,old)=>old.Status=="LOCKED"?throw new InvalidOperationException("Locked period is immutable"):old with{Version=old.Version+1,InputChecksum=checksum,FrozenAt=DateTimeOffset.UtcNow});}
 public PeriodSnapshot Lock(string tenant,string period){var key=$"{tenant}|{period}";if(!periods.TryGetValue(key,out var p))throw new InvalidOperationException("Freeze before lock");var locked=p with{Status="LOCKED"};periods[key]=locked;return locked;}
 public PeriodSnapshot Export(string tenant,string period,string content){var key=$"{tenant}|{period}";if(!periods.TryGetValue(key,out var p))throw new InvalidOperationException("Freeze before export");var result=p with{ExportChecksum=Hash(content)};periods[key]=result;return result;}
 public PeriodSnapshot Amend(string tenant,string lockedPeriod,string newPeriod,string reason){if(string.IsNullOrWhiteSpace(reason))throw new ArgumentException("Amendment reason required");var old=Get(tenant,lockedPeriod);if(old.Status!="LOCKED")throw new InvalidOperationException("Only locked period requires amendment");var amendment=new PeriodSnapshot(Guid.NewGuid().ToString(),tenant,newPeriod,1,"AMENDMENT_DRAFT",Hash(reason),DateTimeOffset.UtcNow,null,old.Id);periods[$"{tenant}|{newPeriod}"]=amendment;return amendment;}
 public PeriodSnapshot Get(string tenant,string period)=>periods.TryGetValue($"{tenant}|{period}",out var p)?p:throw new KeyNotFoundException();public bool IsLocked(string tenant,string period)=>periods.TryGetValue($"{tenant}|{period}",out var p)&&p.Status=="LOCKED";public IReadOnlyList<FinanceEntry> Entries(string tenant,string order)=>entries.Values.Where(x=>x.TenantId==tenant&&x.OrderId==order).OrderBy(x=>x.CreatedAt).ToList();private static string Hash(string value)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(value))).ToLowerInvariant();
}
