using System.Collections.Concurrent;using System.Security.Cryptography;using System.Text;
namespace SanSo.Api.Modules;
public enum OrgRole{Owner,Admin,Finance,Ops,Accountant,Warehouse,Viewer}
public record AppUser(string Id,string Email,string DisplayName,string PasswordHash,string? TotpSecret,bool Disabled=false);
public record Membership(string TenantId,string UserId,OrgRole Role,DateTimeOffset? ExpiresAt=null);
public record SessionPrincipal(string UserId,string TenantId,OrgRole Role,bool StepUpVerified,DateTimeOffset ExpiresAt);
public record SessionToken(string Token,SessionPrincipal Principal);
public sealed class IdentityService
{
 private readonly ConcurrentDictionary<string,AppUser> users=new();private readonly ConcurrentDictionary<string,Membership> memberships=new();private readonly ConcurrentDictionary<string,SessionPrincipal> sessions=new();
 public IdentityService(){var user=Register("owner.an-nhien@example.invalid","Demo Owner","Demo-Only-Password-2026!",GenerateTotpSecret());AddMembership("tenant-an-nhien",user.Id,OrgRole.Owner);}
 public AppUser Register(string email,string displayName,string password,string? totpSecret=null){email=email.Trim().ToLowerInvariant();if(password.Length<14)throw new ArgumentException("Password must contain at least 14 characters");var user=new AppUser(Guid.NewGuid().ToString(),email,displayName,HashPassword(password),totpSecret);if(!users.TryAdd(email,user))throw new InvalidOperationException("Email already exists");return user;}
 public void AddMembership(string tenant,string userId,OrgRole role,DateTimeOffset? expiresAt=null)=>memberships[$"{tenant}|{userId}"]=new(tenant,userId,role,expiresAt);
 public SessionToken Login(string email,string password,string tenant,string? totpCode=null){if(!users.TryGetValue(email.Trim().ToLowerInvariant(),out var user)||user.Disabled||!VerifyPassword(password,user.PasswordHash))throw new UnauthorizedAccessException("Invalid credentials");if(!memberships.TryGetValue($"{tenant}|{user.Id}",out var membership)||membership.ExpiresAt<=DateTimeOffset.UtcNow)throw new UnauthorizedAccessException("No active membership");var needsMfa=membership.Role is OrgRole.Owner or OrgRole.Admin;if(needsMfa&&(user.TotpSecret is null||totpCode is null||!VerifyTotp(user.TotpSecret,totpCode)))throw new UnauthorizedAccessException("MFA_REQUIRED");var raw=Convert.ToHexString(RandomNumberGenerator.GetBytes(32)).ToLowerInvariant();var principal=new SessionPrincipal(user.Id,tenant,membership.Role,needsMfa,DateTimeOffset.UtcNow.AddHours(8));sessions[TokenHash(raw)]=principal;return new(raw,principal);}
 public SessionPrincipal Authenticate(string raw,string tenant){if(!sessions.TryGetValue(TokenHash(raw),out var p)||p.ExpiresAt<=DateTimeOffset.UtcNow||p.TenantId!=tenant)throw new UnauthorizedAccessException("Invalid or expired session");return p;}
 public void Revoke(string raw)=>sessions.TryRemove(TokenHash(raw),out _);
 public void RemoveMembership(string tenant,string userId){memberships.TryRemove($"{tenant}|{userId}",out _);foreach(var session in sessions.Where(x=>x.Value.TenantId==tenant&&x.Value.UserId==userId))sessions.TryRemove(session.Key,out _);}
 public static bool Allows(OrgRole role,string permission)=>permission switch{"organization.manage"=>role is OrgRole.Owner or OrgRole.Admin,"finance.read"=>role is not OrgRole.Warehouse,"tax.review"=>role is OrgRole.Owner or OrgRole.Admin or OrgRole.Finance or OrgRole.Accountant,"inventory.write"=>role is OrgRole.Owner or OrgRole.Admin or OrgRole.Ops or OrgRole.Warehouse,"billing.manage"=>role is OrgRole.Owner,"export.sensitive"=>role is OrgRole.Owner or OrgRole.Admin or OrgRole.Finance or OrgRole.Accountant,_=>false};
 public static string GenerateTotpSecret()=>Convert.ToHexString(RandomNumberGenerator.GetBytes(20));
 public static string CurrentTotp(string secret,DateTimeOffset? now=null){var counter=(now??DateTimeOffset.UtcNow).ToUnixTimeSeconds()/30;Span<byte> data=stackalloc byte[8];for(var i=7;i>=0;i--){data[i]=(byte)(counter&0xff);counter>>=8;}using var hmac=new HMACSHA1(Convert.FromHexString(secret));var hash=hmac.ComputeHash(data.ToArray());var offset=hash[^1]&0x0f;var binary=((hash[offset]&0x7f)<<24)|(hash[offset+1]<<16)|(hash[offset+2]<<8)|hash[offset+3];return(binary%1_000_000).ToString("D6");}
 private static bool VerifyTotp(string secret,string code)=>Enumerable.Range(-1,3).Any(offset=>CryptographicOperations.FixedTimeEquals(Encoding.ASCII.GetBytes(CurrentTotp(secret,DateTimeOffset.UtcNow.AddSeconds(offset*30))),Encoding.ASCII.GetBytes(code)));
 private static string HashPassword(string password){var salt=RandomNumberGenerator.GetBytes(16);var hash=Rfc2898DeriveBytes.Pbkdf2(password,salt,120_000,HashAlgorithmName.SHA256,32);return $"120000.{Convert.ToBase64String(salt)}.{Convert.ToBase64String(hash)}";}
 private static bool VerifyPassword(string password,string encoded){var p=encoded.Split('.');var actual=Rfc2898DeriveBytes.Pbkdf2(password,Convert.FromBase64String(p[1]),int.Parse(p[0]),HashAlgorithmName.SHA256,32);return CryptographicOperations.FixedTimeEquals(actual,Convert.FromBase64String(p[2]));}
 private static string TokenHash(string raw)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(raw)));
}
