using System.Collections.Concurrent;
namespace SanSo.Api.Modules;
public record TeamInvitation(string Id,string TenantId,string Email,OrgRole Role,string TokenHash,DateTimeOffset ExpiresAt,string Status);
public record SupportGrant(string Id,string TenantId,string SupportUserId,string Reason,DateTimeOffset ExpiresAt,string ApprovedBy,string Status);
public sealed class TeamAndSupport
{
 private readonly ConcurrentDictionary<string,TeamInvitation> invitations=new();private readonly ConcurrentDictionary<string,SupportGrant> grants=new();
 public (TeamInvitation Invitation,string RawToken) Invite(string tenant,string email,OrgRole role,DateTimeOffset expiresAt){if(expiresAt<=DateTimeOffset.UtcNow)throw new ArgumentException("Invitation expiry must be future");var raw=Convert.ToHexString(System.Security.Cryptography.RandomNumberGenerator.GetBytes(32));var hash=Convert.ToHexString(System.Security.Cryptography.SHA256.HashData(System.Text.Encoding.UTF8.GetBytes(raw)));var x=new TeamInvitation(Guid.NewGuid().ToString(),tenant,email.Trim().ToLowerInvariant(),role,hash,expiresAt,"PENDING");invitations[x.Id]=x;return(x,raw);}
 public TeamInvitation Accept(string id,string rawToken){if(!invitations.TryGetValue(id,out var x)||x.Status!="PENDING"||x.ExpiresAt<=DateTimeOffset.UtcNow)throw new UnauthorizedAccessException();var hash=Convert.ToHexString(System.Security.Cryptography.SHA256.HashData(System.Text.Encoding.UTF8.GetBytes(rawToken)));if(!System.Security.Cryptography.CryptographicOperations.FixedTimeEquals(System.Text.Encoding.ASCII.GetBytes(hash),System.Text.Encoding.ASCII.GetBytes(x.TokenHash)))throw new UnauthorizedAccessException();var accepted=x with{Status="ACCEPTED"};invitations[id]=accepted;return accepted;}
 public SupportGrant GrantSupport(string tenant,string supportUser,string reason,DateTimeOffset expiresAt,string approvedBy,bool stepUpVerified){if(!stepUpVerified)throw new UnauthorizedAccessException("STEP_UP_REQUIRED");if(string.IsNullOrWhiteSpace(reason)||expiresAt<=DateTimeOffset.UtcNow||expiresAt>DateTimeOffset.UtcNow.AddHours(8))throw new ArgumentException("Support access needs reason and maximum 8-hour future expiry");var g=new SupportGrant(Guid.NewGuid().ToString(),tenant,supportUser,reason,expiresAt,approvedBy,"ACTIVE");grants[g.Id]=g;return g;}
 public bool CanSupportAccess(string tenant,string supportUser)=>grants.Values.Any(x=>x.TenantId==tenant&&x.SupportUserId==supportUser&&x.Status=="ACTIVE"&&x.ExpiresAt>DateTimeOffset.UtcNow);public void RevokeSupport(string id){if(grants.TryGetValue(id,out var g))grants[id]=g with{Status="REVOKED"};}
}
