export type Role='Owner'|'Admin'|'Finance'|'Ops'|'Accountant'|'Warehouse'|'Viewer';
export type Principal={userId:string;tenantId:string;role:Role;stepUpVerified:boolean;expiresAt:string};
export type Session={token:string;principal:Principal};
const base=import.meta.env.VITE_API_URL??'http://localhost:5080';
export async function login(email:string,password:string,tenantId:string,totpCode:string):Promise<Session>{const response=await fetch(`${base}/api/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password,tenantId,totpCode:totpCode||null})});const raw=await decode<{token:string;principal:Omit<Principal,'role'>&{role:Role|number}}>(response);const roles:Role[]=['Owner','Admin','Finance','Ops','Accountant','Warehouse','Viewer'];const role=typeof raw.principal.role==='number'?roles[raw.principal.role]:raw.principal.role;if(!role)throw new Error('ROLE_UNSUPPORTED');return{...raw,principal:{...raw.principal,role}}}
export async function logout(session:Session):Promise<void>{await fetch(`${base}/api/auth/logout`,{method:'POST',headers:authorizedHeaders(session)})}
export async function apiJson<T>(session:Session,path:string,init:RequestInit={}):Promise<T>{const headers=new Headers(init.headers);for(const[key,value]of Object.entries(authorizedHeaders(session)))headers.set(key,value);if(init.body&&!headers.has('Content-Type'))headers.set('Content-Type','application/json');return decode<T>(await fetch(base+path,{...init,headers}))}
export function authorizedHeaders(session:Session):Record<string,string>{return{'X-Tenant-Id':session.principal.tenantId,Authorization:`Bearer ${session.token}`}}
async function decode<T>(response:Response):Promise<T>{const text=await response.text();let body:unknown=text;if(text){try{body=JSON.parse(text)}catch{body=text}}if(!response.ok){const problem=body as{title?:string;code?:string};throw new Error(problem?.title??problem?.code??`HTTP ${response.status}`)}return body as T}
