export type Role='Owner'|'Admin'|'Finance'|'Ops'|'Accountant'|'Warehouse'|'Viewer';
export type Principal={userId:string;tenantId:string;role:Role;stepUpVerified:boolean;expiresAt:string};export type Session={token:string;principal:Principal};
export const apiBase=import.meta.env.VITE_API_URL??'http://localhost:5080';
export async function login(email:string,password:string,tenantId:string,totpCode:string):Promise<Session>{const raw=await publicJson<{token:string;principal:Omit<Principal,'role'>&{role:Role|number}}>('/api/auth/login',{method:'POST',body:JSON.stringify({email,password,tenantId,totpCode:totpCode||null})});const roles:Role[]=['Owner','Admin','Finance','Ops','Accountant','Warehouse','Viewer'];const role=typeof raw.principal.role==='number'?roles[raw.principal.role]:raw.principal.role;if(!role)throw new Error('ROLE_UNSUPPORTED');return{...raw,principal:{...raw.principal,role}}}
export async function logout(session:Session){await apiJson(session,'/api/auth/logout',{method:'POST'})}
export async function apiJson<T>(session:Session,path:string,init:RequestInit={}):Promise<T>{const headers=new Headers(init.headers);for(const[k,v]of Object.entries(authHeaders(session)))headers.set(k,v);if(init.body&&!headers.has('Content-Type'))headers.set('Content-Type','application/json');return decode<T>(await fetch(apiBase+path,{...init,headers}))}
export async function apiUpload<T>(session:Session,path:string,file:File):Promise<T>{const form=new FormData();form.append('file',file);return decode<T>(await fetch(apiBase+path,{method:'POST',headers:authHeaders(session),body:form}))}
export function authHeaders(session:Session):Record<string,string>{return{Authorization:`Bearer ${session.token}`,'X-Tenant-Id':session.principal.tenantId}}
async function publicJson<T>(path:string,init:RequestInit):Promise<T>{const headers=new Headers(init.headers);headers.set('Content-Type','application/json');return decode<T>(await fetch(apiBase+path,{...init,headers}))}
async function decode<T>(response:Response):Promise<T>{const text=await response.text();let body:unknown=text;if(text){try{body=JSON.parse(text)}catch{body=text}}if(!response.ok){const p=body as{title?:string;code?:string};throw new Error(p?.title??p?.code??`HTTP ${response.status}`)}return body as T}
