// @vitest-environment jsdom
import'@testing-library/jest-dom/vitest';import{afterEach,beforeEach,describe,expect,it,vi}from'vitest';import{cleanup,fireEvent,render,screen,waitFor}from'@testing-library/react';import AppV2 from'./AppV2';
const dashboard={gross:2030000,expectedPayout:1847300,actualPayout:1817300,difference:-30000,matched:0,needsReview:1,dataFreshness:'Đồng bộ 2 phút trước',taxStatus:'NEEDS_REVIEW'};const reconciliation={settlementCode:'SET-2026-08-01',gross:2030000,fees:-182700,refunds:0,expected:1847300,actual:1817300,difference:-30000,status:'NEEDS_REVIEW',lines:[{orderCode:'SP-1',type:'SALE',amount:2030000,explanation:'Nguồn đơn'}]};
beforeEach(()=>{vi.stubGlobal('fetch',vi.fn((url:string)=>Promise.resolve({ok:true,json:()=>Promise.resolve(url.includes('dashboard')?dashboard:reconciliation)})));});afterEach(()=>{cleanup();vi.unstubAllGlobals()});
describe('SànSổ V2 workflows',()=>{
 it('renders first reconciliation and data freshness',async()=>{render(<AppV2/>);expect(screen.getByText('Đang tải dữ liệu')).toBeInTheDocument();await waitFor(()=>expect(screen.getByText('SET-2026-08-01')).toBeInTheDocument());expect(screen.getByText(/Chênh lệch 30\.000/)).toBeInTheDocument();expect(screen.getByText(/Đồng bộ 2 phút trước/)).toBeInTheDocument()});
 it('navigates to Tax Center without inventing a rate',async()=>{render(<AppV2/>);await screen.findByText('SET-2026-08-01');fireEvent.click(screen.getByText('Trung tâm thuế'));expect(screen.getByText('Hồ sơ thuế cần rà soát')).toBeInTheDocument();expect(screen.getByText(/Không có thuế suất nào được suy đoán/)).toBeInTheDocument();expect(screen.getByRole('button',{name:/Khóa kỳ/})).toBeDisabled()});
 it('shows inventory quarantine excluded from ATP',async()=>{render(<AppV2/>);await screen.findByText('SET-2026-08-01');fireEvent.click(screen.getByText('Tồn kho'));expect(screen.getByText('Hàng hoàn chờ kiểm')).toBeInTheDocument();expect(screen.getByText('0 (quarantine)')).toBeInTheDocument();expect(screen.getByText(/ATP = on-hand/)).toBeInTheDocument()});
 it('shows degraded integration with safe write-back copy',async()=>{render(<AppV2/>);await screen.findByText('SET-2026-08-01');fireEvent.click(screen.getByText('Nguồn dữ liệu'));expect(screen.getByText('Degraded — token revoked')).toBeInTheDocument();expect(screen.getByText(/checksum \+ preview/)).toBeInTheDocument()});
 it('renders safe error and retry when API fails',async()=>{vi.stubGlobal('fetch',vi.fn(()=>Promise.reject(new Error('offline'))));render(<AppV2/>);await waitFor(()=>expect(screen.getByText('Không thể tải dữ liệu')).toBeInTheDocument());expect(screen.getByText(/Dữ liệu nguồn đã nhận không bị mất/)).toBeInTheDocument();expect(screen.getByRole('button',{name:'Thử lại'})).toBeInTheDocument()});
});
