import{fireEvent,render,screen,waitFor}from'@testing-library/react';import{afterEach,describe,expect,it,vi}from'vitest';import AppV8 from'./AppV8';
afterEach(()=>vi.restoreAllMocks());
const dashboard={gross:2030000,expectedPayout:1900000,actualPayout:1870000,difference:-30000,matched:1,needsReview:1,dataFreshness:'Vừa cập nhật',taxStatus:'NEEDS_REVIEW'};const reconciliation={settlementCode:'SET-2026-08',gross:2030000,fees:-130000,refunds:0,expected:1900000,actual:1870000,difference:-30000,status:'NEEDS_REVIEW',lines:[]};
describe('AppV8 authenticated operations shell',()=>{
 it('loads dashboard through the authenticated tenant client',async()=>{const fetchMock=vi.spyOn(globalThis,'fetch').mockResolvedValueOnce(ok(session(0,'owner-token',true))).mockResolvedValueOnce(ok(dashboard)).mockResolvedValueOnce(ok(reconciliation));render(<AppV8/>);signIn();expect(await screen.findByText('SET-2026-08')).toBeInTheDocument();for(const call of fetchMock.mock.calls.slice(1)){const headers=new Headers((call[1]as RequestInit).headers);expect(headers.get('Authorization')).toBe('Bearer owner-token');expect(headers.get('X-Tenant-Id')).toBe('tenant-an-nhien')}});
 it('shows explicit locked states to Viewer',async()=>{vi.spyOn(globalThis,'fetch').mockResolvedValueOnce(ok(session(6,'viewer-token',false))).mockResolvedValueOnce(ok(dashboard)).mockResolvedValueOnce(ok(reconciliation));render(<AppV8/>);signIn();await screen.findByText('SET-2026-08');fireEvent.click(screen.getByRole('button',{name:'Onboarding'}));expect(screen.getByText('Bạn không có quyền onboarding')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Workflow'}));expect(screen.getByRole('button',{name:/Đã khóa · Tạo partial refund/})).toBeDisabled();expect(screen.getByRole('button',{name:'Kiểm tra Copilot từ chối chọn thuế suất'})).toBeEnabled()});
 it('keeps import behind the authenticated shell',async()=>{vi.spyOn(globalThis,'fetch').mockResolvedValueOnce(ok(session(2,'finance-token',false))).mockResolvedValueOnce(ok(dashboard)).mockResolvedValueOnce(ok(reconciliation));render(<AppV8/>);signIn();await screen.findByText('SET-2026-08');fireEvent.click(screen.getByRole('button',{name:'Import dữ liệu'}));expect(screen.getByText('Import CSV/XLSX có kiểm soát')).toBeInTheDocument();expect(screen.getByLabelText('Chọn file import')).toBeInTheDocument()});
});
function signIn(){fireEvent.change(screen.getByLabelText('Email'),{target:{value:'user@example.invalid'}});fireEvent.change(screen.getByLabelText('Mật khẩu'),{target:{value:'a-long-password'}});fireEvent.change(screen.getByLabelText('Mã MFA 6 số'),{target:{value:'123456'}});fireEvent.click(screen.getByRole('button',{name:'Đăng nhập'}))}
function session(role:number,token:string,mfa:boolean){return{token,principal:{userId:'u1',tenantId:'tenant-an-nhien',role,stepUpVerified:mfa,expiresAt:'2026-08-25T00:00:00Z'}}}function ok(value:unknown){return Promise.resolve(new Response(JSON.stringify(value),{status:200,headers:{'Content-Type':'application/json'}}))}
