import{useState}from'react';import{AlertTriangle,CheckCircle2,FileSpreadsheet,ShieldCheck,X}from'lucide-react';import'./import-workflow.css';

const api=import.meta.env.VITE_API_URL??'http://localhost:5080';
type Row={rowNumber:number;orderCode?:string;amount?:number;occurredAt?:string;errors:string[]};
type Preview={batchId?:string|null;previewToken:string;expiresAt:string;format:string;templateVersion:string;checksum:string;rows:Row[];errors:string[];duplicate:boolean;persisted:boolean};
type Confirmed={batchId?:string|null;checksum:string;acceptedRows:number;rejectedRows:number;duplicate:boolean;persisted:boolean};

export default function ImportConfirmationPanel(){const[open,setOpen]=useState(false),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState<Preview|null>(null),[confirmed,setConfirmed]=useState<Confirmed|null>(null),[armed,setArmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const reset=()=>{setFile(null);setPreview(null);setConfirmed(null);setArmed(false);setError('')};
 const upload=async()=>{if(!file)return;setBusy(true);setError('');try{const form=new FormData();form.append('file',file);const response=await fetch(api+'/api/imports/preview',{method:'POST',headers:{'X-Tenant-Id':'tenant-an-nhien'},body:form});const body=await response.json();if(!response.ok)throw new Error(body.code??`HTTP ${response.status}`);setPreview(body);setConfirmed(null);setArmed(false)}catch(e){setError(e instanceof Error?e.message:'Không thể đọc file')}finally{setBusy(false)}};
 const confirm=async()=>{if(!preview||!armed)return;setBusy(true);setError('');try{const response=await fetch(api+'/api/imports/confirm',{method:'POST',headers:{'Content-Type':'application/json','X-Tenant-Id':'tenant-an-nhien'},body:JSON.stringify({previewToken:preview.previewToken,checksum:preview.checksum})});const body=await response.json();if(!response.ok)throw new Error(body.code??`HTTP ${response.status}`);setConfirmed(body);setArmed(false)}catch(e){setError(e instanceof Error?e.message:'Không thể xác nhận import')}finally{setBusy(false)}};
 return <><button className="import-launch" onClick={()=>setOpen(true)}><FileSpreadsheet/>Import CSV/XLSX có kiểm soát</button>{open&&<div className="import-backdrop"><section className="import-dialog" role="dialog" aria-label="Import dữ liệu có kiểm soát"><header><div><p>PREVIEW → CONFIRM</p><h2>Import dữ liệu giao dịch</h2></div><button aria-label="Đóng import" onClick={()=>setOpen(false)}><X/></button></header><div className="import-content">
 {!preview&&!confirmed&&<div className="import-picker"><FileSpreadsheet/><h3>Chọn file CSV hoặc XLSX</h3><p>Tối đa 10 MB. CSV dùng UTF-8. Công thức XLSX không được thực thi.</p><input aria-label="Chọn file import" type="file" accept=".csv,.xlsx,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={event=>setFile(event.target.files?.[0]??null)}/><button disabled={!file||busy} onClick={upload}>{busy?'Đang kiểm tra…':'Tạo bản xem trước'}</button></div>}
 {preview&&!confirmed&&<><div className="import-summary"><div><span>Định dạng</span><b>{preview.format} · {preview.templateVersion}</b></div><div><span>Dòng hợp lệ</span><b>{preview.rows.filter(x=>x.errors.length===0).length}</b></div><div><span>Dòng lỗi</span><b>{preview.rows.filter(x=>x.errors.length>0).length}</b></div><div><span>Trùng file</span><b>{preview.duplicate?'Có':'Không'}</b></div></div>{!preview.persisted&&<div className="import-warning"><AlertTriangle/><span><b>Development mode</b> Preview này chưa được lưu PostgreSQL; confirm sẽ trả <code>persisted=false</code>.</span></div>}{preview.errors.length>0&&<div className="import-errors">{preview.errors.map(x=><span key={x}>{x}</span>)}</div>}<div className="import-trace"><span>SHA-256 checksum</span><code>{preview.checksum}</code><small>Token hết hạn: {new Date(preview.expiresAt).toLocaleString('vi-VN')}</small></div><div className="import-table"><div className="import-row head"><span>Dòng</span><span>Mã đơn</span><span>Số tiền</span><span>Thời điểm / lỗi</span></div>{preview.rows.slice(0,20).map(row=><div className={'import-row '+(row.errors.length?'invalid':'')} key={row.rowNumber}><span>{row.rowNumber}</span><span>{row.orderCode??'—'}</span><span>{row.amount?.toLocaleString('vi-VN')??'—'}</span><span>{row.errors.length?row.errors.join(', '):row.occurredAt??'—'}</span></div>)}</div>{preview.rows.length>20&&<p className="import-limit">Chỉ hiển thị 20/{preview.rows.length} dòng. Tất cả dòng vẫn được validation.</p>}<label className="import-consent"><input type="checkbox" checked={armed} onChange={event=>setArmed(event.target.checked)}/><span>Tôi đã kiểm tra checksum, số dòng hợp lệ/lỗi và hiểu rằng chỉ dòng hợp lệ được ghi khi xác nhận.</span></label><div className="import-actions"><button onClick={reset}>Chọn file khác</button><button className="primary" disabled={!armed||busy||preview.errors.length>0} onClick={confirm}><ShieldCheck/>{busy?'Đang xác nhận…':'Xác nhận import'}</button></div></>}
 {confirmed&&<div className="import-done"><CheckCircle2/><h3>{confirmed.duplicate?'File đã được xác nhận trước đó':'Đã hoàn tất bước xác nhận'}</h3><p>{confirmed.acceptedRows} dòng được chấp nhận · {confirmed.rejectedRows} dòng bị loại.</p><div className={confirmed.persisted?'persisted':'not-persisted'}>{confirmed.persisted?'Đã ghi raw events vào PostgreSQL.':'Demo only · Chưa ghi PostgreSQL.'}</div><code>{confirmed.checksum}</code><button onClick={reset}>Import file khác</button></div>}{error&&<div className="import-error" role="alert"><AlertTriangle/>{error}</div>}</div><footer>SànSổ không tự tạo tax rate, không tự nộp hồ sơ và không thực thi công thức trong file.</footer></section></div>}</>}
