// @vitest-environment jsdom
import'@testing-library/jest-dom/vitest';import{afterEach,describe,expect,it,vi}from'vitest';import{cleanup,fireEvent,render,screen,waitFor}from'@testing-library/react';import ImportConfirmationPanel from'./ImportConfirmationPanel';

afterEach(()=>{cleanup();vi.unstubAllGlobals()});
const rows=Array.from({length:21},(_,index)=>({rowNumber:index+2,orderCode:`HTTP-${index+1}`,amount:100000+index,occurredAt:'2026-08-24T09:00:00+07:00',errors:index===1?['AMOUNT_INVALID']:[]}));
const preview={batchId:null,previewToken:'token-test',expiresAt:'2026-08-24T10:00:00+07:00',format:'CSV',templateVersion:'csv-v1',checksum:'abc123checksum',rows,errors:[],duplicate:false,persisted:false};

describe('controlled import panel',()=>{
 it('requires preview review and explicit checkbox before confirm',async()=>{const fetchMock=vi.fn().mockResolvedValueOnce({ok:true,json:()=>Promise.resolve(preview)}).mockResolvedValueOnce({ok:true,json:()=>Promise.resolve({batchId:null,checksum:preview.checksum,acceptedRows:20,rejectedRows:1,duplicate:false,persisted:false})});vi.stubGlobal('fetch',fetchMock);render(<ImportConfirmationPanel/>);fireEvent.click(screen.getByText('Import CSV/XLSX có kiểm soát'));const file=new File(['order_code,amount,occurred_at\nHTTP-1,1,2026-08-24'],'orders.csv',{type:'text/csv'});fireEvent.change(screen.getByLabelText('Chọn file import'),{target:{files:[file]}});fireEvent.click(screen.getByText('Tạo bản xem trước'));await screen.findByText('abc123checksum');expect(screen.getByText('Chỉ hiển thị 20/21 dòng. Tất cả dòng vẫn được validation.')).toBeInTheDocument();expect(screen.queryByText('HTTP-21')).not.toBeInTheDocument();expect(screen.getByText('AMOUNT_INVALID')).toBeInTheDocument();const confirm=screen.getByRole('button',{name:/Xác nhận import/});expect(confirm).toBeDisabled();fireEvent.click(screen.getByRole('checkbox'));expect(confirm).toBeEnabled();fireEvent.click(confirm);await screen.findByText('Demo only · Chưa ghi PostgreSQL.');expect(fetchMock).toHaveBeenCalledTimes(2);expect(JSON.parse(fetchMock.mock.calls[1][1].body)).toEqual({previewToken:'token-test',checksum:'abc123checksum'})});
 it('blocks confirm when file-level validation has errors',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:()=>Promise.resolve({...preview,errors:['MISSING_COLUMN:amount']})}));render(<ImportConfirmationPanel/>);fireEvent.click(screen.getByText('Import CSV/XLSX có kiểm soát'));fireEvent.change(screen.getByLabelText('Chọn file import'),{target:{files:[new File(['x'],'bad.csv',{type:'text/csv'})]}});fireEvent.click(screen.getByText('Tạo bản xem trước'));await screen.findByText('MISSING_COLUMN:amount');fireEvent.click(screen.getByRole('checkbox'));expect(screen.getByRole('button',{name:/Xác nhận import/})).toBeDisabled()});
 it('shows safe server error state',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:false,status:400,json:()=>Promise.resolve({code:'UNSUPPORTED_FILE_TYPE'})}));render(<ImportConfirmationPanel/>);fireEvent.click(screen.getByText('Import CSV/XLSX có kiểm soát'));fireEvent.change(screen.getByLabelText('Chọn file import'),{target:{files:[new File(['x'],'bad.exe',{type:'application/octet-stream'})]}});fireEvent.click(screen.getByText('Tạo bản xem trước'));await waitFor(()=>expect(screen.getByRole('alert')).toHaveTextContent('UNSUPPORTED_FILE_TYPE'))});
});
