param([string]$Source='docs/openapi-v12-canonical.json',[string]$Output='docs/openapi-v13-canonical.json')
$ErrorActionPreference='Stop';$d=Get-Content -LiteralPath $Source -Raw -Encoding UTF8|ConvertFrom-Json
$d.info.title='SanSo API V13';$d.info.version='0.13.0-pilot';$d.info.description='Canonical V13 pilot contract. Adds durable settlement CSV/XLSX preview, checksum confirmation, hashed preview tokens and production-safe routing.';$d.'x-sanso-canonical-entrypoint'='backend/SanSo.Api.V6/ProgramCanonicalV13.cs'
$row=[ordered]@{type='object';required=@('sourceLineId','lineType','expectedAmount','actualAmount');properties=[ordered]@{sourceLineId=@{type='string'};orderCode=@{type=@('string','null')};lineType=@{type='string';enum=@('SALE','PLATFORM_FEE','SHIPPING_FEE','AFFILIATE_FEE','REFUND','ADJUSTMENT')};expectedAmount=@{type='integer';format='int64'};actualAmount=@{type='integer';format='int64'}}}
$preview=[ordered]@{type='object';required=@('previewId','previewToken','expiresAt','format','checksum','settlementCode','expectedAmount','actualAmount','difference','lineCount','rows','alreadyConfirmed');properties=[ordered]@{previewId=@{type='string';format='uuid'};previewToken=@{type='string';description='Single-preview secret. Empty only when the same checksum was already confirmed.'};expiresAt=@{type='string';format='date-time'};format=@{type='string';enum=@('CSV','XLSX')};checksum=@{type='string';pattern='^[a-f0-9]{64}$'};settlementCode=@{type='string'};expectedAmount=@{type='integer';format='int64'};actualAmount=@{type='integer';format='int64'};difference=@{type='integer';format='int64'};lineCount=@{type='integer';maximum=10000};rows=@{type='array';items=@{'$ref'='#/components/schemas/SettlementImportRow'}};alreadyConfirmed=@{type='boolean'};confirmedRunId=@{type=@('string','null');format='uuid'}}}
$confirm=[ordered]@{type='object';required=@('previewToken','checksum');properties=[ordered]@{previewToken=@{type='string';minLength=64};checksum=@{type='string';pattern='^[a-f0-9]{64}$'}}}
$d.components.schemas|Add-Member SettlementImportRow $row -Force;$d.components.schemas|Add-Member SettlementPreview $preview -Force;$d.components.schemas|Add-Member SettlementConfirm $confirm -Force
$tenant=@{'$ref'='#/components/parameters/TenantHeader'}
$d.paths.'/api/imports/settlements'.post.requestBody.content.'multipart/form-data'.schema.properties.file.description='UTF-8 CSV or XLSX (no formulas), explicit expected and actual amount per source line; maximum 10 MiB, 10,000 data rows and 20 columns.'
$d.paths.'/api/imports/settlements'.post.responses.'200'.description='Durable preview; no settlement, ledger or reconciliation writes occur before confirmation.';$d.paths.'/api/imports/settlements'.post.responses.'200'.content.'application/json'.schema=@{'$ref'='#/components/schemas/SettlementPreview'}
$d.paths|Add-Member '/api/imports/settlements/confirm' ([ordered]@{post=@{parameters=@($tenant);requestBody=@{required=$true;content=@{'application/json'=@{schema=@{'$ref'='#/components/schemas/SettlementConfirm'}}}};responses=@{'200'=@{description='Confirmed import or idempotent replay';content=@{'application/json'=@{schema=@{'$ref'='#/components/schemas/SettlementImportResult'}}}};'401'=@{'$ref'='#/components/responses/Unauthorized'};'403'=@{'$ref'='#/components/responses/Forbidden'};'409'=@{description='Preview token/checksum invalid or expired'};'503'=@{'$ref'='#/components/responses/ServiceUnavailable'}}}}) -Force
$json=$d|ConvertTo-Json -Depth 100;[System.IO.File]::WriteAllText((Join-Path(Get-Location)$Output),$json+[Environment]::NewLine,[System.Text.UTF8Encoding]::new($false));"OPENAPI_V13_GENERATED=$Output"
