param([string]$Source="backend/SanSo.Api.V6/ProgramCanonicalV12.cs",[string]$Output="backend/SanSo.Api.V6/ProgramCanonicalV13.cs",[string]$Targets="backend/SanSo.Api.V6/Directory.Build.targets",[string]$Props="backend/SanSo.Api.V6/Directory.Build.props")
$ErrorActionPreference="Stop";$text=Get-Content -LiteralPath $Source -Raw -Encoding UTF8;$registration='    builder.Services.AddSingleton<SanSo.Api.V6.PostgresReportExportStoreV1>();';$text=$text.Replace($registration,$registration+[Environment]::NewLine+'    builder.Services.AddSingleton<SanSo.Api.V6.PostgresSettlementImportWorkflowV1>();');$helper='SanSo.Api.V6.PostgresReportExportStoreV1 ReportStore() => app.Services.GetRequiredService<SanSo.Api.V6.PostgresReportExportStoreV1>();';$text=$text.Replace($helper,$helper+[Environment]::NewLine+'SanSo.Api.V6.PostgresSettlementImportWorkflowV1 SettlementWorkflow() => app.Services.GetRequiredService<SanSo.Api.V6.PostgresSettlementImportWorkflowV1>();')
$text=$text.Replace('Prefer(app.MapPost("/api/imports/settlements", async (HttpRequest r, CancellationToken ct) =>','Prefer(app.MapPost("/api/imports/settlements/direct", async (HttpRequest r, CancellationToken ct) =>');$directAnchor='    var principal=Require(r,"tax.review");if(!Db())return Results.Json(new{code="DATABASE_REQUIRED"},statusCode:503);';$text=$text.Replace($directAnchor,$directAnchor);$text=$text.Replace('Prefer(app.MapPost("/api/imports/settlements/direct"','if(app.Environment.IsDevelopment())Prefer(app.MapPost("/api/imports/settlements/direct"')
$anchor='if(app.Environment.IsDevelopment())Prefer(app.MapPost("/api/imports/settlements/direct", async (HttpRequest r, CancellationToken ct) =>';$routes=@'
Prefer(app.MapPost("/api/imports/settlements",async(HttpRequest r,CancellationToken ct)=>
{
    Require(r,"tax.review");if(!Db())return Results.Json(new{code="DATABASE_REQUIRED"},statusCode:503);if(!r.HasFormContentType)return Results.BadRequest(new{code="MULTIPART_REQUIRED"});var file=(await r.ReadFormAsync(ct)).Files.GetFile("file");if(file is null)return Results.BadRequest(new{code="FILE_REQUIRED"});if(file.Length>10*1024*1024)return Results.BadRequest(new{code="FILE_TOO_LARGE"});try{var bytes=SanSo.Api.V6.SettlementFileParserV1.Read(file.OpenReadStream());SanSo.Api.V6.SettlementImportV1 parsed;string format;var ext=Path.GetExtension(file.FileName).ToLowerInvariant();if(ext==".csv"&&file.ContentType is"text/csv"or"application/csv"or"application/vnd.ms-excel"or"application/octet-stream"){parsed=SanSo.Api.V6.SettlementFileParserV1.Csv(bytes);format="CSV";}else if(ext==".xlsx"&&file.ContentType is"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"or"application/octet-stream"){parsed=SanSo.Api.V6.SettlementFileParserV1.Xlsx(bytes);format="XLSX";}else return Results.BadRequest(new{code="UNSUPPORTED_FILE_TYPE"});return Results.Ok(await SettlementWorkflow().Stage(Tenant(r),parsed,format,ct));}catch(DecoderFallbackException){return Results.BadRequest(new{code="ENCODING_INVALID",hint="Save CSV as UTF-8"});}catch(InvalidDataException e){return Results.BadRequest(new{code=e.Message});}catch(OverflowException){return Results.BadRequest(new{code="AMOUNT_SUM_OVERFLOW"});}
}));
Prefer(app.MapPost("/api/imports/settlements/confirm",async(HttpRequest r,SanSo.Api.V6.SettlementConfirmRequestV1 b,CancellationToken ct)=>{var p=Require(r,"tax.review");if(!Db())return Results.Json(new{code="DATABASE_REQUIRED"},statusCode:503);return Results.Ok(await SettlementWorkflow().Confirm(Tenant(r),b,p.UserId,ct));}));

'@
if(-not$text.Contains($anchor)){throw'DIRECT_ROUTE_ANCHOR_NOT_FOUND'};$text=$text.Replace($anchor,$routes+$anchor);$text=$text.Replace('api = "v12"','api = "v13"');$text=$text.Replace('var app = builder.Build();','var app = builder.Build();'+[Environment]::NewLine+'SanSo.Api.V6.DevelopmentE2ESeedV2.Apply(app);');[System.IO.File]::WriteAllText((Join-Path(Get-Location)$Output),$text,[System.Text.UTF8Encoding]::new($false));$t=Get-Content -LiteralPath $Targets -Raw -Encoding UTF8;$t=$t.Replace('ProgramCanonicalV12.cs','ProgramCanonicalV13.cs');[System.IO.File]::WriteAllText((Join-Path(Get-Location)$Targets),$t,[System.Text.UTF8Encoding]::new($false));$p=Get-Content -LiteralPath $Props -Raw -Encoding UTF8;if(-not$p.Contains('SettlementImportWorkflowV1.cs')){$p=$p.Replace('    <Compile Include="PostgresReportExportStoreV1.cs" />','    <Compile Include="PostgresReportExportStoreV1.cs" />'+[Environment]::NewLine+'    <Compile Include="SettlementImportWorkflowV1.cs" />')};[System.IO.File]::WriteAllText((Join-Path(Get-Location)$Props),$p,[System.Text.UTF8Encoding]::new($false));"API_V13_ENTRYPOINT_GENERATED=$Output"
