param([string]$Source="docs/openapi-v11-canonical.json",[string]$Output="docs/openapi-v12-canonical.json")
$ErrorActionPreference="Stop";$d=Get-Content -LiteralPath $Source -Raw -Encoding UTF8|ConvertFrom-Json;$d.info.title="SanSo API V12";$d.info.version="0.12.0-pilot";$d.info.description="Canonical V12 pilot contract. Adds step-up protected durable report preview, checksum confirmation and download.";$d.'x-sanso-canonical-entrypoint'="backend/SanSo.Api.V6/ProgramCanonicalV12.cs";$tenant=@{'$ref'="#/components/parameters/TenantHeader"};$id=@{name="id";in="path";required=$true;schema=@{type="string";format="uuid"}}
$request=[ordered]@{type="object";required=@("runId");properties=@{runId=@{type="string";format="uuid"}}};$confirm=[ordered]@{type="object";required=@("contentChecksum");properties=@{contentChecksum=@{type="string";pattern="^[a-f0-9]{64}$"}}};$preview=[ordered]@{type="object";required=@("exportId","type","status","fileName","contentType","contentChecksum","inputChecksum","lineCount","generatedAt","expiresAt");properties=[ordered]@{exportId=@{type="string";format="uuid"};type=@{type="string";const="RECONCILIATION_CSV"};status=@{type="string";enum=@("PREVIEWED","READY")};fileName=@{type="string"};contentType=@{type="string";const="text/csv"};contentChecksum=@{type="string"};inputChecksum=@{type="string"};lineCount=@{type="integer"};generatedAt=@{type="string";format="date-time"};expiresAt=@{type="string";format="date-time"}}};$d.components.schemas|Add-Member ExportRequest $request -Force;$d.components.schemas|Add-Member ExportConfirm $confirm -Force;$d.components.schemas|Add-Member ExportPreview $preview -Force
$d.paths|Add-Member '/api/reports' ([ordered]@{get=@{parameters=@($tenant);responses=@{'200'=@{description="Report catalog"};'401'=@{'$ref'="#/components/responses/Unauthorized"};'403'=@{'$ref'="#/components/responses/Forbidden"}}}}) -Force
$d.paths|Add-Member '/api/reports/exports' ([ordered]@{post=@{parameters=@($tenant);requestBody=@{required=$true;content=@{'application/json'=@{schema=@{'$ref'="#/components/schemas/ExportRequest"}}}};responses=@{'200'=@{description="Durable preview requiring checksum confirmation";content=@{'application/json'=@{schema=@{'$ref'="#/components/schemas/ExportPreview"}}}};'403'=@{'$ref'="#/components/responses/Forbidden"};'404'=@{description="Reconciliation not found"};'503'=@{'$ref'="#/components/responses/ServiceUnavailable"}}}}) -Force
$d.paths|Add-Member '/api/reports/exports/{id}/confirm' ([ordered]@{post=@{parameters=@($tenant,$id);requestBody=@{required=$true;content=@{'application/json'=@{schema=@{'$ref'="#/components/schemas/ExportConfirm"}}}};responses=@{'200'=@{description="READY export metadata";content=@{'application/json'=@{schema=@{'$ref'="#/components/schemas/ExportPreview"}}}};'403'=@{'$ref'="#/components/responses/Forbidden"};'409'=@{description="Checksum mismatch or preview expired"}}}}) -Force
$d.paths|Add-Member '/api/reports/exports/{id}' ([ordered]@{get=@{parameters=@($tenant,$id);responses=@{'200'=@{description="Export metadata";content=@{'application/json'=@{schema=@{'$ref'="#/components/schemas/ExportPreview"}}}};'403'=@{'$ref'="#/components/responses/Forbidden"};'404'=@{description="Export not found"}}}}) -Force
$d.paths|Add-Member '/api/reports/exports/{id}/download' ([ordered]@{get=@{parameters=@($tenant,$id);responses=@{'200'=@{description="Confirmed traceable CSV";content=@{'text/csv'=@{schema=@{type="string"}}}};'403'=@{'$ref'="#/components/responses/Forbidden"};'409'=@{description="Export not ready or expired"}}}}) -Force
$json=$d|ConvertTo-Json -Depth 100;[System.IO.File]::WriteAllText((Join-Path(Get-Location)$Output),$json+[Environment]::NewLine,[System.Text.UTF8Encoding]::new($false));"OPENAPI_V12_GENERATED=$Output"

