param([string]$Source="backend/SanSo.Api.V6/ProgramCanonicalV11.cs",[string]$Output="backend/SanSo.Api.V6/ProgramCanonicalV12.cs",[string]$Targets="backend/SanSo.Api.V6/Directory.Build.targets",[string]$Props="backend/SanSo.Api.V6/Directory.Build.props")
$ErrorActionPreference="Stop";$text=Get-Content -LiteralPath $Source -Raw -Encoding UTF8;$registration='    builder.Services.AddSingleton<SanSo.Api.V6.PostgresSettlementImportStoreV1>();';$text=$text.Replace($registration,$registration+[Environment]::NewLine+'    builder.Services.AddSingleton<SanSo.Api.V6.PostgresReportExportStoreV1>();');$helper='SanSo.Api.V6.PostgresSettlementImportStoreV1 SettlementStore() => app.Services.GetRequiredService<SanSo.Api.V6.PostgresSettlementImportStoreV1>();';$text=$text.Replace($helper,$helper+[Environment]::NewLine+'SanSo.Api.V6.PostgresReportExportStoreV1 ReportStore() => app.Services.GetRequiredService<SanSo.Api.V6.PostgresReportExportStoreV1>();')
$anchor='Prefer(app.MapPost("/api/imports/settlements", async (HttpRequest r, CancellationToken ct) =>';$routes=@'
Prefer(app.MapGet("/api/reports",(HttpRequest r)=>{Require(r,"export.sensitive");return Results.Ok(new{items=SanSo.Api.V6.PostgresReportExportStoreV1.Catalog()});}));
Prefer(app.MapPost("/api/reports/exports",async(HttpRequest r,V12ExportRequest b,CancellationToken ct)=>{var p=Require(r,"export.sensitive");if(!p.StepUpVerified)throw new ForbiddenException();if(!Db())return Results.Json(new{code="DATABASE_REQUIRED"},statusCode:503);try{return Results.Ok(await ReportStore().Preview(Tenant(r),b.RunId,p.UserId,ct));}catch(KeyNotFoundException){return Results.NotFound(new{code="RECONCILIATION_NOT_FOUND"});}}));
Prefer(app.MapPost("/api/reports/exports/{id}/confirm",async(HttpRequest r,string id,V12ExportConfirm b,CancellationToken ct)=>{var p=Require(r,"export.sensitive");if(!p.StepUpVerified)throw new ForbiddenException();if(!Db())return Results.Json(new{code="DATABASE_REQUIRED"},statusCode:503);return Results.Ok(await ReportStore().Confirm(Tenant(r),id,b.ContentChecksum,p.UserId,ct));}));
Prefer(app.MapGet("/api/reports/exports/{id}",async(HttpRequest r,string id,CancellationToken ct)=>{Require(r,"export.sensitive");if(!Db())return Results.Json(new{code="DATABASE_REQUIRED"},statusCode:503);var item=await ReportStore().Get(Tenant(r),id,ct);return item is null?Results.NotFound(new{code="EXPORT_NOT_FOUND"}):Results.Ok(item);}));
Prefer(app.MapGet("/api/reports/exports/{id}/download",async(HttpRequest r,string id,CancellationToken ct)=>{var p=Require(r,"export.sensitive");if(!p.StepUpVerified)throw new ForbiddenException();if(!Db())return Results.Json(new{code="DATABASE_REQUIRED"},statusCode:503);try{var file=await ReportStore().Download(Tenant(r),id,p.UserId,ct);return Results.File(file.Content,file.ContentType,file.FileName,enableRangeProcessing:false);}catch(KeyNotFoundException){return Results.NotFound(new{code="EXPORT_NOT_FOUND"});}}));

'@
if(-not$text.Contains($anchor)){throw'SETTLEMENT_ROUTE_ANCHOR_NOT_FOUND'};$text=$text.Replace($anchor,$routes+$anchor);$text=$text.Replace('api = "v11"','api = "v12"');$text=$text.Replace('record V8NotificationBody(NotificationType Type, DeliveryChannel Channel, string Recipient, string ResourceRef, DateTimeOffset WindowStart);','record V8NotificationBody(NotificationType Type, DeliveryChannel Channel, string Recipient, string ResourceRef, DateTimeOffset WindowStart);'+[Environment]::NewLine+'record V12ExportRequest(string RunId);'+[Environment]::NewLine+'record V12ExportConfirm(string ContentChecksum);');[System.IO.File]::WriteAllText((Join-Path(Get-Location)$Output),$text,[System.Text.UTF8Encoding]::new($false));$t=Get-Content -LiteralPath $Targets -Raw -Encoding UTF8;$t=$t.Replace('ProgramCanonicalV11.cs','ProgramCanonicalV12.cs');[System.IO.File]::WriteAllText((Join-Path(Get-Location)$Targets),$t,[System.Text.UTF8Encoding]::new($false));$p=Get-Content -LiteralPath $Props -Raw -Encoding UTF8;if(-not$p.Contains('PostgresReportExportStoreV1.cs')){$p=$p.Replace('    <Compile Include="PostgresSettlementImportStoreV1.cs" />','    <Compile Include="PostgresSettlementImportStoreV1.cs" />'+[Environment]::NewLine+'    <Compile Include="PostgresReportExportStoreV1.cs" />')};[System.IO.File]::WriteAllText((Join-Path(Get-Location)$Props),$p,[System.Text.UTF8Encoding]::new($false));"API_V12_ENTRYPOINT_GENERATED=$Output"
