param([string]$Source="docs/openapi-v9-canonical.json",[string]$Output="docs/openapi-v11-canonical.json")
$ErrorActionPreference="Stop";$d=Get-Content -LiteralPath $Source -Raw -Encoding UTF8|ConvertFrom-Json;$d.info.title="SanSo API V11";$d.info.version="0.11.0-pilot";$d.info.description="Canonical V11 pilot contract. Adds traceable settlement CSV ingestion and line reconciliation. No endpoint submits tax filings or tax payments.";$d.'x-sanso-canonical-entrypoint'="backend/SanSo.Api.V6/ProgramCanonicalV11.cs"
$tenant=@{'$ref'="#/components/parameters/TenantHeader"};$run=@{name="runId";in="path";required=$true;schema=@{type="string";format="uuid"}}
$result=[ordered]@{type="object";required=@("settlementId","runId","settlementCode","expectedAmount","actualAmount","difference","status","lineCount","duplicate");properties=[ordered]@{settlementId=@{type="string";format="uuid"};runId=@{type="string";format="uuid"};settlementCode=@{type="string"};expectedAmount=@{type="integer";format="int64"};actualAmount=@{type="integer";format="int64"};difference=@{type="integer";format="int64"};status=@{type="string";enum=@("MATCHED","NEEDS_REVIEW")};lineCount=@{type="integer"};duplicate=@{type="boolean"}}}
$line=[ordered]@{type="object";required=@("sourceLineId","type","expectedAmount","actualAmount","difference","reasonCode","ledgerSourceKey","explanation","rawSourceEventId");properties=[ordered]@{sourceLineId=@{type="string"};sourceOrderCode=@{type=@("string","null")};type=@{type="string"};expectedAmount=@{type="integer";format="int64"};actualAmount=@{type="integer";format="int64"};difference=@{type="integer";format="int64"};reasonCode=@{type="string"};ledgerSourceKey=@{type="string"};explanation=@{type="string"};rawSourceEventId=@{type="string"}}}
$detail=[ordered]@{type="object";required=@("runId","settlementCode","status","expectedAmount","actualAmount","difference","inputChecksum","createdAt","lines");properties=[ordered]@{runId=@{type="string";format="uuid"};settlementCode=@{type="string"};status=@{type="string"};expectedAmount=@{type="integer";format="int64"};actualAmount=@{type="integer";format="int64"};difference=@{type="integer";format="int64"};inputChecksum=@{type="string"};createdAt=@{type="string";format="date-time"};lines=@{type="array";items=@{'$ref'="#/components/schemas/SettlementReconciliationLine"}}}}
$d.components.schemas|Add-Member SettlementImportResult $result -Force;$d.components.schemas|Add-Member SettlementReconciliationLine $line -Force;$d.components.schemas|Add-Member SettlementReconciliationDetail $detail -Force
$d.paths|Add-Member '/api/imports/settlements' ([ordered]@{post=[ordered]@{parameters=@($tenant);requestBody=@{required=$true;content=@{'multipart/form-data'=@{schema=@{type="object";required=@("file");properties=@{file=@{type="string";format="binary";maxLength=10485760;description="UTF-8 CSV with explicit expected and actual amount per source line"}}}}}};responses=[ordered]@{'200'=@{description="Imported or idempotent replay";content=@{'application/json'=@{schema=@{'$ref'="#/components/schemas/SettlementImportResult"}}}};'400'=@{'$ref'="#/components/responses/BadRequest"};'401'=@{'$ref'="#/components/responses/Unauthorized"};'403'=@{'$ref'="#/components/responses/Forbidden"};'409'=@{description="Same settlement code with a different file"};'503'=@{'$ref'="#/components/responses/ServiceUnavailable"}}}}) -Force
$d.paths|Add-Member '/api/reconciliations/{runId}' ([ordered]@{get=[ordered]@{parameters=@($tenant,$run);responses=[ordered]@{'200'=@{description="Raw-to-ledger-to-reconciliation line drill-down";content=@{'application/json'=@{schema=@{'$ref'="#/components/schemas/SettlementReconciliationDetail"}}}};'400'=@{'$ref'="#/components/responses/BadRequest"};'401'=@{'$ref'="#/components/responses/Unauthorized"};'403'=@{'$ref'="#/components/responses/Forbidden"};'404'=@{description="Run not found in tenant"};'503'=@{'$ref'="#/components/responses/ServiceUnavailable"}}}}) -Force
$json=$d|ConvertTo-Json -Depth 100;[System.IO.File]::WriteAllText((Join-Path(Get-Location)$Output),$json+[Environment]::NewLine,[System.Text.UTF8Encoding]::new($false));"OPENAPI_V11_GENERATED=$Output"

