using System.Security.Cryptography;
using System.Text;
using Npgsql;

namespace SanSo.Api.V6;

public sealed record ReportCatalogItemV1(string Code,string Format,string Description,bool RequiresStepUp);
public sealed record ExportPreviewV1(string ExportId,string Type,string Status,string FileName,string ContentType,string ContentChecksum,string InputChecksum,int LineCount,DateTimeOffset GeneratedAt,DateTimeOffset ExpiresAt);
public sealed record ExportDownloadV1(string FileName,string ContentType,byte[] Content,string Checksum);

public sealed class PostgresReportExportStoreV1(NpgsqlDataSource dataSource)
{
    public static IReadOnlyList<ReportCatalogItemV1> Catalog()=>[new("RECONCILIATION_CSV","CSV","Line-level settlement reconciliation with raw and ledger trace metadata.",true)];
    public async Task<ExportPreviewV1> Preview(string tenant,string runId,string actor,CancellationToken ct)
    {
        var tenantId=Guid.Parse(tenant);if(!Guid.TryParse(runId,out var runGuid))throw new ArgumentException("RUN_ID_INVALID");await using var c=await dataSource.OpenConnectionAsync(ct);await using var tx=await c.BeginTransactionAsync(ct);await SetTenant(c,tx,tenant,ct);
        await using var header=c.CreateCommand();header.Transaction=tx;header.CommandText="SELECT s.code,r.status,r.expected_amount,r.actual_amount,r.difference,r.input_checksum FROM reconciliation_runs r JOIN settlements s ON s.id=r.settlement_id WHERE r.organization_id=$1 AND r.id=$2";header.Parameters.AddWithValue(tenantId);header.Parameters.AddWithValue(runGuid);await using var hr=await header.ExecuteReaderAsync(ct);if(!await hr.ReadAsync(ct))throw new KeyNotFoundException("RECONCILIATION_NOT_FOUND");var settlement=hr.GetString(0);var status=hr.GetString(1);var expected=hr.GetInt64(2);var actual=hr.GetInt64(3);var difference=hr.GetInt64(4);var inputChecksum=hr.GetString(5);await hr.CloseAsync();
        await using var lines=c.CreateCommand();lines.Transaction=tx;lines.CommandText="SELECT rl.source_line_id,rl.source_order_code,ll.type,rl.expected_amount,rl.actual_amount,rl.difference,rl.reason_code,ll.source_key,re.source_event_id FROM reconciliation_lines rl JOIN ledger_lines ll ON ll.id=rl.ledger_line_id JOIN raw_events re ON re.id=ll.raw_event_id WHERE rl.organization_id=$1 AND rl.run_id=$2 ORDER BY rl.source_line_id";lines.Parameters.AddWithValue(tenantId);lines.Parameters.AddWithValue(runGuid);await using var reader=await lines.ExecuteReaderAsync(ct);var rows=new List<string>();while(await reader.ReadAsync(ct))rows.Add(string.Join(',',Csv(reader.GetString(0)),Csv(reader.IsDBNull(1)?"":reader.GetString(1)),Csv(reader.GetString(2)),reader.GetInt64(3),reader.GetInt64(4),reader.GetInt64(5),Csv(reader.GetString(6)),Csv(reader.GetString(7)),Csv(reader.GetString(8))));await reader.CloseAsync();
        var generated=DateTimeOffset.UtcNow;var metadata=$"# tenant={tenant}; run={runId}; settlement={SafeMeta(settlement)}; status={status}; expected={expected}; actual={actual}; difference={difference}; input_checksum={inputChecksum}; rule_versions=none; generated_at={generated:O}\r\n";var csv=metadata+"source_line_id,order_code,type,expected_amount,actual_amount,difference,reason_code,ledger_source_key,raw_source_event_id\r\n"+string.Join("\r\n",rows)+"\r\n";var content=Encoding.UTF8.GetBytes(csv);var checksum=Hash(content);var expires=generated.AddMinutes(30);var fileName=$"reconciliation-{FilePart(settlement)}-{runId}.csv";var exportId=await Scalar(c,tx,"INSERT INTO exports(organization_id,type,status,input_checksum,rule_versions,generated_by,generated_at,file_ref,content_type,content_bytes,content_checksum,expires_at)VALUES($1,'RECONCILIATION_CSV','PREVIEWED',$2,'[]'::jsonb,$3::uuid,$4,$5,'text/csv',$6,$7,$8)RETURNING id::text",ct,tenantId,inputChecksum,actor,generated,fileName,content,checksum,expires);await Audit(c,tx,tenantId,actor,"EXPORT_PREVIEW",exportId,checksum,ct);await tx.CommitAsync(ct);return new(exportId,"RECONCILIATION_CSV","PREVIEWED",fileName,"text/csv",checksum,inputChecksum,rows.Count,generated,expires);
    }
    public async Task<ExportPreviewV1> Confirm(string tenant,string exportId,string checksum,string actor,CancellationToken ct){var tenantId=Guid.Parse(tenant);if(!Guid.TryParse(exportId,out var id))throw new ArgumentException("EXPORT_ID_INVALID");await using var c=await dataSource.OpenConnectionAsync(ct);await using var tx=await c.BeginTransactionAsync(ct);await SetTenant(c,tx,tenant,ct);await using var q=c.CreateCommand();q.Transaction=tx;q.CommandText="UPDATE exports SET status='READY',confirmed_at=now(),expires_at=now()+interval '24 hours' WHERE organization_id=$1 AND id=$2 AND status='PREVIEWED' AND expires_at>now() AND content_checksum=$3 RETURNING id::text,type,status,file_ref,content_type,content_checksum,input_checksum,generated_at,expires_at";q.Parameters.AddWithValue(tenantId);q.Parameters.AddWithValue(id);q.Parameters.AddWithValue(checksum);await using var r=await q.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))throw new InvalidOperationException("EXPORT_CONFIRMATION_INVALID_OR_EXPIRED");var result=new ExportPreviewV1(r.GetString(0),r.GetString(1),r.GetString(2),r.GetString(3),r.GetString(4),r.GetString(5),r.GetString(6),0,r.GetFieldValue<DateTimeOffset>(7),r.GetFieldValue<DateTimeOffset>(8));await r.CloseAsync();await Audit(c,tx,tenantId,actor,"EXPORT_CONFIRM",exportId,checksum,ct);await tx.CommitAsync(ct);return result;}
    public async Task<ExportPreviewV1?> Get(string tenant,string exportId,CancellationToken ct){var tenantId=Guid.Parse(tenant);if(!Guid.TryParse(exportId,out var id))return null;await using var c=await dataSource.OpenConnectionAsync(ct);await using var tx=await c.BeginTransactionAsync(ct);await SetTenant(c,tx,tenant,ct);await using var q=c.CreateCommand();q.Transaction=tx;q.CommandText="SELECT id::text,type,status,file_ref,content_type,content_checksum,input_checksum,generated_at,expires_at FROM exports WHERE organization_id=$1 AND id=$2";q.Parameters.AddWithValue(tenantId);q.Parameters.AddWithValue(id);await using var r=await q.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))return null;return new(r.GetString(0),r.GetString(1),r.GetString(2),r.GetString(3),r.GetString(4),r.GetString(5),r.GetString(6),0,r.GetFieldValue<DateTimeOffset>(7),r.GetFieldValue<DateTimeOffset>(8));}
    public async Task<ExportDownloadV1> Download(string tenant,string exportId,string actor,CancellationToken ct){var tenantId=Guid.Parse(tenant);if(!Guid.TryParse(exportId,out var id))throw new KeyNotFoundException("EXPORT_NOT_FOUND");await using var c=await dataSource.OpenConnectionAsync(ct);await using var tx=await c.BeginTransactionAsync(ct);await SetTenant(c,tx,tenant,ct);await using var q=c.CreateCommand();q.Transaction=tx;q.CommandText="UPDATE exports SET download_count=download_count+1 WHERE organization_id=$1 AND id=$2 AND status='READY' AND expires_at>now() RETURNING file_ref,content_type,content_bytes,content_checksum";q.Parameters.AddWithValue(tenantId);q.Parameters.AddWithValue(id);await using var r=await q.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))throw new InvalidOperationException("EXPORT_NOT_READY_OR_EXPIRED");var result=new ExportDownloadV1(r.GetString(0),r.GetString(1),(byte[])r[2],r.GetString(3));await r.CloseAsync();await Audit(c,tx,tenantId,actor,"EXPORT_DOWNLOAD",exportId,result.Checksum,ct);await tx.CommitAsync(ct);return result;}
    private static async Task Audit(NpgsqlConnection c,NpgsqlTransaction tx,Guid tenant,string actor,string action,string id,string reason,CancellationToken ct)=>await Execute(c,tx,"INSERT INTO audit_logs(organization_id,actor_id,action,resource_type,resource_id,reason,correlation_id,entry_hash)VALUES($1,$2::uuid,$3,'EXPORT',$4,$5,$6,$7)",ct,tenant,actor,action,id,reason,Guid.NewGuid().ToString("N"),Hash(Encoding.UTF8.GetBytes($"{tenant}|{actor}|{action}|{id}|{reason}")));
    private static async Task SetTenant(NpgsqlConnection c,NpgsqlTransaction tx,string tenant,CancellationToken ct)=>await Execute(c,tx,"SELECT set_config('app.current_organization_id',$1,true)",ct,tenant);
    private static async Task<string> Scalar(NpgsqlConnection c,NpgsqlTransaction tx,string sql,CancellationToken ct,params object[] values){await using var q=c.CreateCommand();q.Transaction=tx;q.CommandText=sql;foreach(var value in values)q.Parameters.AddWithValue(value);return(await q.ExecuteScalarAsync(ct))?.ToString()??throw new InvalidOperationException("EXPORT_WRITE_FAILED");}
    private static async Task Execute(NpgsqlConnection c,NpgsqlTransaction tx,string sql,CancellationToken ct,params object[] values){await using var q=c.CreateCommand();q.Transaction=tx;q.CommandText=sql;foreach(var value in values)q.Parameters.AddWithValue(value);await q.ExecuteNonQueryAsync(ct);}
    private static string Csv(string value){var safe=value.Length>0&&value[0]is'='or'+'or'-'or'@'?"'"+value:value;return'"'+safe.Replace("\"","\"\"")+'"';}
    private static string SafeMeta(string value)=>value.Replace("\r"," ").Replace("\n"," ").Replace(";",",");
    private static string FilePart(string value)=>string.Concat(value.Where(c=>char.IsLetterOrDigit(c)||c is'-'or'_')).PadRight(1,'x');
    private static string Hash(byte[] value)=>Convert.ToHexString(SHA256.HashData(value)).ToLowerInvariant();
}
