using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Npgsql;

namespace SanSo.Api.V6;

public sealed record SettlementImportRowV1(int RowNumber,string SourceLineId,string? OrderCode,string LineType,long ExpectedAmount,long ActualAmount);
public sealed record SettlementImportV1(string Checksum,string SettlementCode,DateTimeOffset PaidAt,string Currency,IReadOnlyList<SettlementImportRowV1> Rows);
public sealed record SettlementImportResultV1(string SettlementId,string RunId,string SettlementCode,long ExpectedAmount,long ActualAmount,long Difference,string Status,int LineCount,bool Duplicate);

public static class SettlementCsvParserV1
{
    private const int MaxBytes=10*1024*1024;
    private static readonly string[] Required=["settlement_code","paid_at","source_line_id","order_code","line_type","expected_amount","actual_amount"];
    private static readonly HashSet<string> Types=new(["SALE","PLATFORM_FEE","SHIPPING_FEE","AFFILIATE_FEE","REFUND","ADJUSTMENT"],StringComparer.Ordinal);
    public static SettlementImportV1 Parse(Stream input)
    {
        using var memory=new MemoryStream();input.CopyTo(memory);if(memory.Length>MaxBytes)throw new InvalidDataException("FILE_TOO_LARGE");var bytes=memory.ToArray();var text=new UTF8Encoding(false,true).GetString(RemoveBom(bytes));var lines=text.Replace("\r\n","\n").Replace('\r','\n').Split('\n',StringSplitOptions.RemoveEmptyEntries);if(lines.Length<2)throw new InvalidDataException("SETTLEMENT_FILE_EMPTY");var delimiter=Detect(lines[0]);var headers=ParseLine(lines[0],delimiter).Select(x=>x.Trim().TrimStart('\uFEFF').ToLowerInvariant()).ToList();foreach(var required in Required)if(!headers.Contains(required,StringComparer.Ordinal))throw new InvalidDataException($"MISSING_COLUMN:{required}");var rows=new List<SettlementImportRowV1>();string? code=null;DateTimeOffset? paidAt=null;for(var i=1;i<lines.Length;i++){var cells=ParseLine(lines[i],delimiter);var raw=headers.Select((h,n)=>(h,v:n<cells.Count?cells[n].Trim():"")).ToDictionary(x=>x.h,x=>x.v,StringComparer.Ordinal);var row=i+1;var currentCode=RequiredText(raw,"settlement_code",row);GuardFormula(currentCode,"settlement_code",row);code??=currentCode;if(code!=currentCode)throw new InvalidDataException($"ROW_{row}:SETTLEMENT_CODE_INCONSISTENT");var paid=ParseDate(RequiredText(raw,"paid_at",row),row);paidAt??=paid;if(paidAt!=paid)throw new InvalidDataException($"ROW_{row}:PAID_AT_INCONSISTENT");var source=RequiredText(raw,"source_line_id",row);GuardFormula(source,"source_line_id",row);var order=raw["order_code"];if(order.Length>0)GuardFormula(order,"order_code",row);var type=RequiredText(raw,"line_type",row).ToUpperInvariant();if(!Types.Contains(type))throw new InvalidDataException($"ROW_{row}:LINE_TYPE_UNSUPPORTED");rows.Add(new(row,source,order.Length==0?null:order,type,ParseAmount(raw["expected_amount"],"EXPECTED_AMOUNT",row),ParseAmount(raw["actual_amount"],"ACTUAL_AMOUNT",row)));}if(rows.Select(x=>x.SourceLineId).Distinct(StringComparer.Ordinal).Count()!=rows.Count)throw new InvalidDataException("SOURCE_LINE_ID_DUPLICATE");return new(Hash(bytes),code!,paidAt!.Value,"VND",rows);
    }
    private static string RequiredText(Dictionary<string,string> raw,string key,int row)=>string.IsNullOrWhiteSpace(raw[key])?throw new InvalidDataException($"ROW_{row}:{key.ToUpperInvariant()}_REQUIRED"):raw[key];
    private static long ParseAmount(string value,string field,int row){if(!long.TryParse(value,NumberStyles.Integer,CultureInfo.InvariantCulture,out var amount))throw new InvalidDataException($"ROW_{row}:{field}_INVALID");return amount;}
    private static DateTimeOffset ParseDate(string value,int row){string[] formats=["yyyy-MM-dd'T'HH:mm:ssK","yyyy-MM-dd HH:mm:ss","yyyy-MM-dd","dd/MM/yyyy HH:mm:ss","dd/MM/yyyy"];if(!DateTimeOffset.TryParseExact(value,formats,CultureInfo.InvariantCulture,DateTimeStyles.AssumeUniversal,out var date))throw new InvalidDataException($"ROW_{row}:PAID_AT_INVALID");return date.Offset==TimeSpan.Zero?date.ToOffset(TimeSpan.FromHours(7)):date;}
    private static void GuardFormula(string value,string field,int row){if(value.Length>0&&value[0]is'='or'+'or'-'or'@')throw new InvalidDataException($"ROW_{row}:{field.ToUpperInvariant()}_FORMULA_NOT_ALLOWED");}
    private static char Detect(string line)=>new[]{',',';','\t'}.OrderByDescending(x=>line.Count(c=>c==x)).First();
    private static List<string> ParseLine(string line,char delimiter){var result=new List<string>();var value=new StringBuilder();var quoted=false;for(var i=0;i<line.Length;i++){var c=line[i];if(c=='"'){if(quoted&&i+1<line.Length&&line[i+1]=='"'){value.Append('"');i++;}else quoted=!quoted;}else if(c==delimiter&&!quoted){result.Add(value.ToString());value.Clear();}else value.Append(c);}if(quoted)throw new InvalidDataException("CSV_QUOTE_UNTERMINATED");result.Add(value.ToString());return result;}
    private static byte[] RemoveBom(byte[] x)=>x.Length>=3&&x[0]==0xef&&x[1]==0xbb&&x[2]==0xbf?x[3..]:x;
    private static string Hash(byte[] x)=>Convert.ToHexString(SHA256.HashData(x)).ToLowerInvariant();
}

public sealed class PostgresSettlementImportStoreV1(NpgsqlDataSource dataSource)
{
    public async Task<SettlementImportResultV1> Import(string tenant,SettlementImportV1 import,string actor,CancellationToken ct)
    {
        var tenantId=Guid.Parse(tenant);await using var c=await dataSource.OpenConnectionAsync(ct);await using var tx=await c.BeginTransactionAsync(ct);await SetTenant(c,tx,tenant,ct);
        var duplicate=await Existing(c,tx,tenantId,import.Checksum,ct);if(duplicate is not null){await tx.CommitAsync(ct);return duplicate with{Duplicate=true};}
        var existingSettlement=await SettlementByCode(c,tx,tenantId,import.SettlementCode,ct);if(existingSettlement is not null)throw new InvalidOperationException("SETTLEMENT_CODE_CONFLICT");
        var batchId=await Scalar(c,tx,"INSERT INTO import_batches(organization_id,source,file_name,checksum,status,accepted_count)VALUES($1,'SETTLEMENT_CSV','settlements.csv',$2,'CONFIRMED',$3)RETURNING id::text",ct,tenantId,import.Checksum,import.Rows.Count);
        var actual=checked(import.Rows.Sum(x=>x.ActualAmount));var expected=checked(import.Rows.Sum(x=>x.ExpectedAmount));var settlementId=await Scalar(c,tx,"INSERT INTO settlements(organization_id,code,actual_amount,currency,paid_at)VALUES($1,$2,$3,$4,$5)RETURNING id::text",ct,tenantId,import.SettlementCode,actual,import.Currency,import.PaidAt.ToUniversalTime());
        var lineData=new List<(SettlementImportRowV1 Row,string LedgerId)>();string? firstRaw=null;
        foreach(var row in import.Rows){var payload=JsonSerializer.Serialize(new{import.SettlementCode,import.PaidAt,row.SourceLineId,row.OrderCode,row.LineType,row.ExpectedAmount,row.ActualAmount});var rawId=await Scalar(c,tx,"INSERT INTO raw_events(organization_id,import_batch_id,source,source_event_id,event_type,schema_version,payload,checksum,occurred_at)VALUES($1,$2::uuid,'SETTLEMENT_CSV',$3,'SETTLEMENT_LINE','settlement-csv-v1',$4::jsonb,$5,$6)RETURNING id::text",ct,tenantId,batchId,$"settlement:{import.Checksum}:{row.SourceLineId}",payload,Hash(payload),import.PaidAt.ToUniversalTime());firstRaw??=rawId;var orderId=await OptionalScalar(c,tx,"SELECT id::text FROM orders WHERE organization_id=$1 AND code=$2 ORDER BY occurred_at DESC LIMIT 1",ct,tenantId,row.OrderCode??"");var explanation=$"Settlement {import.SettlementCode}; source line {row.SourceLineId}; type {row.LineType}; source order {row.OrderCode??"unmatched"}.";var ledgerId=await Scalar(c,tx,"INSERT INTO ledger_lines(organization_id,order_id,raw_event_id,settlement_id,type,amount,currency,source_key,explanation,occurred_at)VALUES($1,NULLIF($2,'')::uuid,$3::uuid,$4::uuid,$5,$6,$7,$8,$9,$10)RETURNING id::text",ct,tenantId,orderId??"",rawId,settlementId,row.LineType,row.ExpectedAmount,import.Currency,$"settlement:{import.SettlementCode}:{row.SourceLineId}",explanation,import.PaidAt.ToUniversalTime());lineData.Add((row,ledgerId));}
        await Execute(c,tx,"UPDATE settlements SET raw_event_id=$2::uuid WHERE id=$1::uuid",ct,settlementId,firstRaw!);var difference=checked(actual-expected);var status=difference==0&&import.Rows.All(x=>x.ActualAmount==x.ExpectedAmount)?"MATCHED":"NEEDS_REVIEW";var runId=await Scalar(c,tx,"INSERT INTO reconciliation_runs(organization_id,settlement_id,status,expected_amount,actual_amount,difference,mapping_version,input_checksum)VALUES($1,$2::uuid,$3,$4,$5,$6,1,$7)RETURNING id::text",ct,tenantId,settlementId,status,expected,actual,difference,import.Checksum);
        foreach(var item in lineData){var diff=checked(item.Row.ActualAmount-item.Row.ExpectedAmount);var reason=item.Row.OrderCode is null?"ORDER_REFERENCE_MISSING":diff==0?"MATCHED":"LINE_AMOUNT_MISMATCH";await Execute(c,tx,"INSERT INTO reconciliation_lines(organization_id,run_id,ledger_line_id,expected_amount,actual_amount,difference,reason_code,source_line_id,source_order_code)VALUES($1,$2::uuid,$3::uuid,$4,$5,$6,$7,$8,NULLIF($9,'') )",ct,tenantId,runId,item.LedgerId,item.Row.ExpectedAmount,item.Row.ActualAmount,diff,reason,item.Row.SourceLineId,item.Row.OrderCode??"");}
        await Execute(c,tx,"INSERT INTO audit_logs(organization_id,actor_id,action,resource_type,resource_id,reason,correlation_id,entry_hash)VALUES($1,$2::uuid,'SETTLEMENT_IMPORT','RECONCILIATION_RUN',$3,'Explicit confirmed CSV import',$4,$5)",ct,tenantId,actor,runId,import.Checksum,Hash($"{tenant}|{actor}|{runId}|{import.Checksum}"));await tx.CommitAsync(ct);return new(settlementId,runId,import.SettlementCode,expected,actual,difference,status,import.Rows.Count,false);
    }
    public async Task<object?> GetRun(string tenant,string runId,CancellationToken ct){var tenantId=Guid.Parse(tenant);await using var c=await dataSource.OpenConnectionAsync(ct);await using var tx=await c.BeginTransactionAsync(ct);await SetTenant(c,tx,tenant,ct);await using var q=c.CreateCommand();q.Transaction=tx;q.CommandText="SELECT r.id::text,s.code,r.status,r.expected_amount,r.actual_amount,r.difference,r.input_checksum,r.created_at FROM reconciliation_runs r JOIN settlements s ON s.id=r.settlement_id WHERE r.organization_id=$1 AND r.id=$2::uuid";q.Parameters.AddWithValue(tenantId);q.Parameters.AddWithValue(runId);await using var reader=await q.ExecuteReaderAsync(ct);if(!await reader.ReadAsync(ct))return null;var header=new{RunId=reader.GetString(0),SettlementCode=reader.GetString(1),Status=reader.GetString(2),ExpectedAmount=reader.GetInt64(3),ActualAmount=reader.GetInt64(4),Difference=reader.GetInt64(5),InputChecksum=reader.GetString(6),CreatedAt=reader.GetFieldValue<DateTimeOffset>(7)};await reader.CloseAsync();await using var lines=c.CreateCommand();lines.Transaction=tx;lines.CommandText="SELECT rl.source_line_id,rl.source_order_code,ll.type,rl.expected_amount,rl.actual_amount,rl.difference,rl.reason_code,ll.source_key,ll.explanation,re.source_event_id FROM reconciliation_lines rl JOIN ledger_lines ll ON ll.id=rl.ledger_line_id JOIN raw_events re ON re.id=ll.raw_event_id WHERE rl.organization_id=$1 AND rl.run_id=$2::uuid ORDER BY rl.source_line_id";lines.Parameters.AddWithValue(tenantId);lines.Parameters.AddWithValue(runId);await using var lr=await lines.ExecuteReaderAsync(ct);var details=new List<object>();while(await lr.ReadAsync(ct))details.Add(new{SourceLineId=lr.GetString(0),SourceOrderCode=lr.IsDBNull(1)?null:lr.GetString(1),Type=lr.GetString(2),ExpectedAmount=lr.GetInt64(3),ActualAmount=lr.GetInt64(4),Difference=lr.GetInt64(5),ReasonCode=lr.GetString(6),LedgerSourceKey=lr.GetString(7),Explanation=lr.GetString(8),RawSourceEventId=lr.GetString(9)});await lr.CloseAsync();await tx.CommitAsync(ct);return new{header.RunId,header.SettlementCode,header.Status,header.ExpectedAmount,header.ActualAmount,header.Difference,header.InputChecksum,header.CreatedAt,Lines=details};}
    private static async Task<SettlementImportResultV1?> Existing(NpgsqlConnection c,NpgsqlTransaction tx,Guid tenant,string checksum,CancellationToken ct){await using var q=c.CreateCommand();q.Transaction=tx;q.CommandText="SELECT s.id::text,r.id::text,s.code,r.expected_amount,r.actual_amount,r.difference,r.status,(SELECT count(*)::int FROM reconciliation_lines l WHERE l.run_id=r.id) FROM reconciliation_runs r JOIN settlements s ON s.id=r.settlement_id WHERE r.organization_id=$1 AND r.input_checksum=$2 LIMIT 1";q.Parameters.AddWithValue(tenant);q.Parameters.AddWithValue(checksum);await using var r=await q.ExecuteReaderAsync(ct);return await r.ReadAsync(ct)?new(r.GetString(0),r.GetString(1),r.GetString(2),r.GetInt64(3),r.GetInt64(4),r.GetInt64(5),r.GetString(6),r.GetInt32(7),true):null;}
    private static async Task<string?> SettlementByCode(NpgsqlConnection c,NpgsqlTransaction tx,Guid tenant,string code,CancellationToken ct)=>await OptionalScalar(c,tx,"SELECT id::text FROM settlements WHERE organization_id=$1 AND code=$2",ct,tenant,code);
    private static async Task SetTenant(NpgsqlConnection c,NpgsqlTransaction tx,string tenant,CancellationToken ct)=>await Execute(c,tx,"SELECT set_config('app.current_organization_id',$1,true)",ct,tenant);
    private static async Task<string> Scalar(NpgsqlConnection c,NpgsqlTransaction tx,string sql,CancellationToken ct,params object[] values)=>await OptionalScalar(c,tx,sql,ct,values)??throw new InvalidOperationException("SETTLEMENT_IMPORT_WRITE_FAILED");
    private static async Task<string?> OptionalScalar(NpgsqlConnection c,NpgsqlTransaction tx,string sql,CancellationToken ct,params object[] values){await using var q=c.CreateCommand();q.Transaction=tx;q.CommandText=sql;foreach(var value in values)q.Parameters.AddWithValue(value);return(await q.ExecuteScalarAsync(ct))?.ToString();}
    private static async Task Execute(NpgsqlConnection c,NpgsqlTransaction tx,string sql,CancellationToken ct,params object[] values){await using var q=c.CreateCommand();q.Transaction=tx;q.CommandText=sql;foreach(var value in values)q.Parameters.AddWithValue(value);await q.ExecuteNonQueryAsync(ct);}
    private static string Hash(string value)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(value))).ToLowerInvariant();
}
