using System.Security.Cryptography;
using System.Text;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Spreadsheet;
using Npgsql;

namespace SanSo.Api.V6;

public sealed class PostgresReportExportStoreV2(NpgsqlDataSource dataSource)
{
    private readonly PostgresReportExportStoreV1 csv=new(dataSource);
    private sealed record Line(string SourceLineId,string OrderCode,string Type,long Expected,long Actual,long Difference,string ReasonCode,string LedgerSourceKey,string RawSourceEventId);
    public static IReadOnlyList<ReportCatalogItemV1> Catalog()=>[new("RECONCILIATION_CSV","CSV","Line-level settlement reconciliation with raw and ledger trace metadata.",true),new("RECONCILIATION_XLSX","XLSX","Formula-free workbook with metadata and line-level reconciliation evidence.",true)];
    public Task<ExportPreviewV1> Preview(string tenant,string runId,string actor,string? type,CancellationToken ct)=>string.IsNullOrWhiteSpace(type)||type=="RECONCILIATION_CSV"?csv.Preview(tenant,runId,actor,ct):type=="RECONCILIATION_XLSX"?PreviewXlsx(tenant,runId,actor,ct):throw new ArgumentException("EXPORT_TYPE_UNSUPPORTED");
    public Task<ExportPreviewV1> Confirm(string tenant,string exportId,string checksum,string actor,CancellationToken ct)=>csv.Confirm(tenant,exportId,checksum,actor,ct);
    public Task<ExportPreviewV1?> Get(string tenant,string exportId,CancellationToken ct)=>csv.Get(tenant,exportId,ct);
    public Task<ExportDownloadV1> Download(string tenant,string exportId,string actor,CancellationToken ct)=>csv.Download(tenant,exportId,actor,ct);
    private async Task<ExportPreviewV1> PreviewXlsx(string tenant,string runId,string actor,CancellationToken ct)
    {
        var tenantId=Guid.Parse(tenant);if(!Guid.TryParse(runId,out var runGuid))throw new ArgumentException("RUN_ID_INVALID");await using var c=await dataSource.OpenConnectionAsync(ct);await using var tx=await c.BeginTransactionAsync(ct);await SetTenant(c,tx,tenant,ct);
        await using var header=c.CreateCommand();header.Transaction=tx;header.CommandText="SELECT s.code,r.status,r.expected_amount,r.actual_amount,r.difference,r.input_checksum FROM reconciliation_runs r JOIN settlements s ON s.id=r.settlement_id WHERE r.organization_id=$1 AND r.id=$2";header.Parameters.AddWithValue(tenantId);header.Parameters.AddWithValue(runGuid);await using var hr=await header.ExecuteReaderAsync(ct);if(!await hr.ReadAsync(ct))throw new KeyNotFoundException("RECONCILIATION_NOT_FOUND");var settlement=hr.GetString(0);var status=hr.GetString(1);var expected=hr.GetInt64(2);var actual=hr.GetInt64(3);var difference=hr.GetInt64(4);var inputChecksum=hr.GetString(5);await hr.CloseAsync();
        await using var lines=c.CreateCommand();lines.Transaction=tx;lines.CommandText="SELECT rl.source_line_id,rl.source_order_code,ll.type,rl.expected_amount,rl.actual_amount,rl.difference,rl.reason_code,ll.source_key,re.source_event_id FROM reconciliation_lines rl JOIN ledger_lines ll ON ll.id=rl.ledger_line_id JOIN raw_events re ON re.id=ll.raw_event_id WHERE rl.organization_id=$1 AND rl.run_id=$2 ORDER BY rl.source_line_id";lines.Parameters.AddWithValue(tenantId);lines.Parameters.AddWithValue(runGuid);await using var reader=await lines.ExecuteReaderAsync(ct);var rows=new List<Line>();while(await reader.ReadAsync(ct))rows.Add(new(reader.GetString(0),reader.IsDBNull(1)?"":reader.GetString(1),reader.GetString(2),reader.GetInt64(3),reader.GetInt64(4),reader.GetInt64(5),reader.GetString(6),reader.GetString(7),reader.GetString(8)));await reader.CloseAsync();
        var generated=DateTimeOffset.UtcNow;var content=Workbook(tenant,runId,settlement,status,expected,actual,difference,inputChecksum,generated,rows);var checksum=Hash(content);var expires=generated.AddMinutes(30);var fileName=$"reconciliation-{FilePart(settlement)}-{runId}.xlsx";var exportId=await Scalar(c,tx,"INSERT INTO exports(organization_id,type,status,input_checksum,rule_versions,generated_by,generated_at,file_ref,content_type,content_bytes,content_checksum,expires_at)VALUES($1,'RECONCILIATION_XLSX','PREVIEWED',$2,'[]'::jsonb,$3::uuid,$4,$5,'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',$6,$7,$8)RETURNING id::text",ct,tenantId,inputChecksum,actor,generated,fileName,content,checksum,expires);await Audit(c,tx,tenantId,actor,"EXPORT_PREVIEW",exportId,checksum,ct);await tx.CommitAsync(ct);return new(exportId,"RECONCILIATION_XLSX","PREVIEWED",fileName,"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",checksum,inputChecksum,rows.Count,generated,expires);
    }
    private static byte[] Workbook(string tenant,string runId,string settlement,string status,long expected,long actual,long difference,string inputChecksum,DateTimeOffset generated,IReadOnlyList<Line> rows)
    {
        using var stream=new MemoryStream();using(var document=SpreadsheetDocument.Create(stream,SpreadsheetDocumentType.Workbook,true)){var workbook=document.AddWorkbookPart();workbook.Workbook=new Workbook();var sheets=workbook.Workbook.AppendChild(new Sheets());var metadata=workbook.AddNewPart<WorksheetPart>();var md=new SheetData();metadata.Worksheet=new Worksheet(md);var fields=new[]{("tenant",tenant),("run_id",runId),("settlement",settlement),("status",status),("expected",expected.ToString()),("actual",actual.ToString()),("difference",difference.ToString()),("input_checksum",inputChecksum),("rule_versions","none"),("generated_at",generated.ToString("O"))};foreach(var field in fields)md.Append(new Row(Text(field.Item1),Text(field.Item2)));sheets.Append(new Sheet{Id=workbook.GetIdOfPart(metadata),SheetId=1,Name="Metadata"});var detail=workbook.AddNewPart<WorksheetPart>();var data=new SheetData();detail.Worksheet=new Worksheet(data);data.Append(new Row(new[]{"source_line_id","order_code","type","expected_amount","actual_amount","difference","reason_code","ledger_source_key","raw_source_event_id"}.Select(Text)));foreach(var row in rows)data.Append(new Row(Text(row.SourceLineId),Text(row.OrderCode),Text(row.Type),Number(row.Expected),Number(row.Actual),Number(row.Difference),Text(row.ReasonCode),Text(row.LedgerSourceKey),Text(row.RawSourceEventId)));sheets.Append(new Sheet{Id=workbook.GetIdOfPart(detail),SheetId=2,Name="Reconciliation"});workbook.Workbook.Save();}return stream.ToArray();
    }
    private static Cell Text(string value)=>new(){DataType=CellValues.InlineString,InlineString=new InlineString(new Text(value??""){Space=SpaceProcessingModeValues.Preserve})};
    private static Cell Number(long value)=>new(){DataType=CellValues.Number,CellValue=new CellValue(value.ToString(System.Globalization.CultureInfo.InvariantCulture))};
    private static async Task Audit(NpgsqlConnection c,NpgsqlTransaction tx,Guid tenant,string actor,string action,string id,string reason,CancellationToken ct)=>await Execute(c,tx,"INSERT INTO audit_logs(organization_id,actor_id,action,resource_type,resource_id,reason,correlation_id,entry_hash)VALUES($1,$2::uuid,$3,'EXPORT',$4,$5,$6,$7)",ct,tenant,actor,action,id,reason,Guid.NewGuid().ToString("N"),Hash(Encoding.UTF8.GetBytes($"{tenant}|{actor}|{action}|{id}|{reason}")));
    private static async Task SetTenant(NpgsqlConnection c,NpgsqlTransaction tx,string tenant,CancellationToken ct)=>await Execute(c,tx,"SELECT set_config('app.current_organization_id',$1,true)",ct,tenant);
    private static async Task<string> Scalar(NpgsqlConnection c,NpgsqlTransaction tx,string sql,CancellationToken ct,params object[] values){await using var q=c.CreateCommand();q.Transaction=tx;q.CommandText=sql;foreach(var value in values)q.Parameters.AddWithValue(value);return(await q.ExecuteScalarAsync(ct))?.ToString()??throw new InvalidOperationException("EXPORT_WRITE_FAILED");}
    private static async Task Execute(NpgsqlConnection c,NpgsqlTransaction tx,string sql,CancellationToken ct,params object[] values){await using var q=c.CreateCommand();q.Transaction=tx;q.CommandText=sql;foreach(var value in values)q.Parameters.AddWithValue(value);await q.ExecuteNonQueryAsync(ct);}
    private static string FilePart(string value)=>string.Concat(value.Where(c=>char.IsLetterOrDigit(c)||c is'-'or'_')).PadRight(1,'x');
    private static string Hash(byte[] value)=>Convert.ToHexString(SHA256.HashData(value)).ToLowerInvariant();
}
