BEGIN;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE organizations(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), slug text NOT NULL UNIQUE, name text NOT NULL,
 timezone text NOT NULL DEFAULT 'Asia/Ho_Chi_Minh', currency char(3) NOT NULL DEFAULT 'VND', created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE users(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), email text NOT NULL UNIQUE, display_name text NOT NULL, password_hash text NOT NULL, mfa_enabled boolean NOT NULL DEFAULT false, disabled_at timestamptz);
CREATE TABLE memberships(organization_id uuid NOT NULL REFERENCES organizations(id),user_id uuid NOT NULL REFERENCES users(id),role text NOT NULL CHECK(role IN('OWNER','ADMIN','FINANCE','OPS','ACCOUNTANT','WAREHOUSE','VIEWER')),expires_at timestamptz,PRIMARY KEY(organization_id,user_id));
CREATE TABLE tax_profiles(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations(id),subject_type text NOT NULL,residency_status text,method text,effective_from date NOT NULL,effective_to date,evidence_ref text,status text NOT NULL DEFAULT 'NEEDS_REVIEW');

CREATE TABLE connections(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations(id),channel text NOT NULL,external_shop_id text NOT NULL,status text NOT NULL,capabilities jsonb NOT NULL DEFAULT '{}',token_ciphertext bytea,last_sync_at timestamptz,UNIQUE(organization_id,channel,external_shop_id));
CREATE TABLE import_batches(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations(id),source text NOT NULL,file_name text,checksum text NOT NULL,status text NOT NULL,accepted_count int NOT NULL DEFAULT 0,duplicate_count int NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(organization_id,checksum));
CREATE TABLE raw_events(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations(id),connection_id uuid REFERENCES connections(id),import_batch_id uuid REFERENCES import_batches(id),source text NOT NULL,source_event_id text NOT NULL,event_type text NOT NULL,schema_version text NOT NULL,payload jsonb NOT NULL,checksum text NOT NULL,occurred_at timestamptz,received_at timestamptz NOT NULL DEFAULT now(),UNIQUE(organization_id,source,source_event_id));
CREATE TABLE inbox_messages(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations(id),source text NOT NULL,message_id text NOT NULL,processed_at timestamptz,error text,UNIQUE(organization_id,source,message_id));
CREATE TABLE outbox_messages(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations(id),type text NOT NULL,payload jsonb NOT NULL,correlation_id text NOT NULL,attempt int NOT NULL DEFAULT 0,next_attempt_at timestamptz,status text NOT NULL DEFAULT 'PENDING',created_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE products(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations(id),name text NOT NULL,canonical_sku text NOT NULL,UNIQUE(organization_id,canonical_sku));
CREATE TABLE channel_skus(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations(id),product_id uuid NOT NULL REFERENCES products(id),connection_id uuid REFERENCES connections(id),channel_sku text NOT NULL,mapping_version int NOT NULL DEFAULT 1,status text NOT NULL DEFAULT 'CONFIRMED',UNIQUE(organization_id,connection_id,channel_sku));
CREATE TABLE orders(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations(id),raw_event_id uuid REFERENCES raw_events(id),channel text NOT NULL,source_key text NOT NULL,code text NOT NULL,status text NOT NULL,gross_amount bigint NOT NULL,currency char(3) NOT NULL DEFAULT 'VND',occurred_at timestamptz NOT NULL,UNIQUE(organization_id,source_key));
CREATE TABLE order_items(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations(id),order_id uuid NOT NULL REFERENCES orders(id),product_id uuid REFERENCES products(id),source_sku text NOT NULL,quantity int NOT NULL CHECK(quantity>0),gross_amount bigint NOT NULL,category_code text);
CREATE TABLE ledger_lines(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations(id),order_id uuid REFERENCES orders(id),raw_event_id uuid REFERENCES raw_events(id),reversal_of_id uuid REFERENCES ledger_lines(id),type text NOT NULL,amount bigint NOT NULL,currency char(3) NOT NULL DEFAULT 'VND',source_key text NOT NULL,explanation text NOT NULL,occurred_at timestamptz NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(organization_id,source_key));
CREATE TABLE settlements(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations(id),raw_event_id uuid REFERENCES raw_events(id),code text NOT NULL,actual_amount bigint NOT NULL,currency char(3) NOT NULL DEFAULT 'VND',paid_at timestamptz NOT NULL,UNIQUE(organization_id,code));
CREATE TABLE reconciliation_runs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations(id),settlement_id uuid NOT NULL REFERENCES settlements(id),status text NOT NULL,expected_amount bigint NOT NULL,actual_amount bigint NOT NULL,difference bigint NOT NULL,mapping_version int NOT NULL,input_checksum text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE reconciliation_lines(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations(id),run_id uuid NOT NULL REFERENCES reconciliation_runs(id),ledger_line_id uuid REFERENCES ledger_lines(id),expected_amount bigint NOT NULL,actual_amount bigint,difference bigint NOT NULL,reason_code text,resolution_note text,resolved_by uuid REFERENCES users(id),resolved_at timestamptz);

CREATE TABLE tax_rule_versions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),code text NOT NULL,version int NOT NULL,jurisdiction text NOT NULL,subject_type text NOT NULL,channel_scope text,category_scope text,effective_from date NOT NULL,effective_to date,legal_source text NOT NULL,legal_article text,status text NOT NULL CHECK(status IN('DRAFT','APPROVED','RETIRED')),formula jsonb NOT NULL,required_inputs jsonb NOT NULL,approved_by uuid REFERENCES users(id),approved_at timestamptz,UNIQUE(code,version));
CREATE TABLE tax_periods(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations(id),period_key text NOT NULL,status text NOT NULL CHECK(status IN('DRAFT','NEEDS_REVIEW','REVIEWED','READY_TO_EXPORT','EXPORTED','LOCKED','AMENDED')),input_checksum text,locked_at timestamptz,locked_by uuid REFERENCES users(id),reopen_reason text,UNIQUE(organization_id,period_key));
CREATE TABLE tax_calculations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations(id),period_id uuid NOT NULL REFERENCES tax_periods(id),ledger_line_id uuid NOT NULL REFERENCES ledger_lines(id),rule_version_id uuid REFERENCES tax_rule_versions(id),status text NOT NULL,basis_amount bigint,calculated_amount bigint,platform_withheld_amount bigint,difference bigint,source_ref text,effective_date date,explanation text NOT NULL,input_snapshot jsonb NOT NULL,calculated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE tax_exceptions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations(id),period_id uuid NOT NULL REFERENCES tax_periods(id),calculation_id uuid REFERENCES tax_calculations(id),code text NOT NULL,severity text NOT NULL,status text NOT NULL DEFAULT 'OPEN',details jsonb NOT NULL,resolved_by uuid REFERENCES users(id),resolution_reason text,resolved_at timestamptz);

CREATE TABLE inventory_locations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations(id),code text NOT NULL,name text NOT NULL,UNIQUE(organization_id,code));
CREATE TABLE inventory_movements(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations(id),product_id uuid NOT NULL REFERENCES products(id),location_id uuid NOT NULL REFERENCES inventory_locations(id),order_id uuid REFERENCES orders(id),type text NOT NULL,quantity int NOT NULL,source_key text NOT NULL,quality_status text NOT NULL DEFAULT 'SELLABLE',occurred_at timestamptz NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(organization_id,source_key));
CREATE TABLE inventory_balances(organization_id uuid NOT NULL REFERENCES organizations(id),product_id uuid NOT NULL REFERENCES products(id),location_id uuid NOT NULL REFERENCES inventory_locations(id),on_hand int NOT NULL,reserved int NOT NULL,quarantine int NOT NULL,version bigint NOT NULL DEFAULT 0,PRIMARY KEY(organization_id,product_id,location_id),CHECK(reserved>=0),CHECK(quarantine>=0));

CREATE TABLE alerts(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations(id),type text NOT NULL,severity text NOT NULL,status text NOT NULL,title text NOT NULL,details jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),acknowledged_at timestamptz);
CREATE TABLE plans(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),code text NOT NULL UNIQUE,name text NOT NULL,monthly_price bigint NOT NULL,annual_price bigint NOT NULL,entitlements jsonb NOT NULL);
CREATE TABLE subscriptions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations(id),plan_id uuid NOT NULL REFERENCES plans(id),status text NOT NULL,trial_ends_at timestamptz,current_period_end timestamptz,external_reference text,UNIQUE(organization_id));
CREATE TABLE exports(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations(id),type text NOT NULL,status text NOT NULL,period_key text,input_checksum text,rule_versions jsonb NOT NULL DEFAULT '[]',generated_by uuid REFERENCES users(id),generated_at timestamptz,file_ref text);
CREATE TABLE audit_logs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid REFERENCES organizations(id),actor_id uuid REFERENCES users(id),action text NOT NULL,resource_type text NOT NULL,resource_id text,reason text,correlation_id text NOT NULL,ip_hash text,previous_hash text,entry_hash text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());

CREATE INDEX ix_raw_events_org_received ON raw_events(organization_id,received_at DESC);
CREATE INDEX ix_ledger_org_occurred ON ledger_lines(organization_id,occurred_at DESC);
CREATE INDEX ix_outbox_pending ON outbox_messages(status,next_attempt_at);
CREATE INDEX ix_alerts_org_status ON alerts(organization_id,status,created_at DESC);
COMMIT;
