using System.Text;using DocumentFormat.OpenXml;using DocumentFormat.OpenXml.Packaging;using DocumentFormat.OpenXml.Spreadsheet;using SanSo.Import;using Xunit;
namespace SanSo.Import.Tests;
public class ImporterTests
{
 [Fact]public void VietnameseSemicolonHeadersAndDateAreNormalized(){var p=Csv("t1","Mã đơn;Số tiền;Ngày đơn\nSP-1;1.250.000;24/08/2026");Assert.Equal(';',p.Delimiter);Assert.Empty(p.Errors);Assert.Equal("SP-1",p.Rows[0].OrderCode);Assert.Equal(1_250_000,p.Rows[0].Amount);Assert.Equal(TimeSpan.FromHours(7),p.Rows[0].OccurredAt!.Value.Offset);}
 [Fact]public void DuplicateFileIsReportedWithoutChangingPreview(){var registry=new ImportRegistry();var importer=new CommerceFileImporter(registry);var bytes=Encoding.UTF8.GetBytes("order_code,amount,occurred_at\no1,100,2026-08-24");Assert.False(importer.PreviewCsv("t1",new MemoryStream(bytes)).Duplicate);var second=importer.PreviewCsv("t1",new MemoryStream(bytes));Assert.True(second.Duplicate);Assert.Single(second.Rows);}
 [Fact]public void MissingColumnsAndBadValuesAreExplicit(){var p=Csv("t1","order id,amount\n,abc");Assert.Contains("MISSING_COLUMN:occurred_at",p.Errors);Assert.Contains("ORDER_CODE_REQUIRED",p.Rows[0].Errors);Assert.Contains("AMOUNT_INVALID",p.Rows[0].Errors);Assert.Contains("DATE_REQUIRED",p.Rows[0].Errors);}
 [Fact]public void CsvQuotedDelimiterDoesNotSplitValue(){var p=Csv("t1","order_code,amount,occurred_at,note\no1,100,2026-08-24,\"a,b\"");Assert.Equal("a,b",p.Rows[0].Raw["note"]);}
 [Fact]public void OversizedFileIsRejectedBeforeParsing(){var importer=new CommerceFileImporter(new());using var stream=new MemoryStream(new byte[10*1024*1024+1]);Assert.Throws<InvalidDataException>(()=>importer.PreviewCsv("t1",stream));}
 [Fact]public void XlsxFormulaIsNeverEvaluatedAndRaisesError(){using var stream=XlsxWithFormula();var p=new CommerceFileImporter(new()).PreviewXlsx("t1",stream);Assert.Contains("FORMULA_NOT_ALLOWED",p.Rows[0].Errors);}
 private static ImportPreview Csv(string tenant,string value)=>new CommerceFileImporter(new()).PreviewCsv(tenant,new MemoryStream(Encoding.UTF8.GetBytes(value)));
 private static MemoryStream XlsxWithFormula(){var m=new MemoryStream();using(var doc=SpreadsheetDocument.Create(m,SpreadsheetDocumentType.Workbook,true)){var wb=doc.AddWorkbookPart();wb.Workbook=new Workbook();var ws=wb.AddNewPart<WorksheetPart>();var data=new SheetData();ws.Worksheet=new Worksheet(data);var sheets=wb.Workbook.AppendChild(new Sheets());sheets.Append(new Sheet{Id=wb.GetIdOfPart(ws),SheetId=1,Name="Import"});data.Append(Row("order_code","amount","occurred_at"));var row=new Row();row.Append(new Cell{DataType=CellValues.String,CellValue=new CellValue("o1")});row.Append(new Cell{CellFormula=new CellFormula("1+1"),CellValue=new CellValue("2")});row.Append(new Cell{DataType=CellValues.String,CellValue=new CellValue("2026-08-24")});data.Append(row);wb.Workbook.Save();}m.Position=0;return m;}private static Row Row(params string[] values){var r=new Row();foreach(var v in values)r.Append(new Cell{DataType=CellValues.String,CellValue=new CellValue(v)});return r;}
}
